// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: animals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAnimalImage = `-- name: AddAnimalImage :one
INSERT INTO animal_images (animal_id, storage_key, alt_text, position)
VALUES ($1, $2, $3, $4)
RETURNING id, animal_id, storage_key, alt_text, position, moderation_status, moderated_by, moderated_at, removed_at, created_at
`

type AddAnimalImageParams struct {
	AnimalID   pgtype.UUID `db:"animal_id" json:"animal_id"`
	StorageKey string      `db:"storage_key" json:"storage_key"`
	AltText    string      `db:"alt_text" json:"alt_text"`
	Position   int16       `db:"position" json:"position"`
}

func (q *Queries) AddAnimalImage(ctx context.Context, arg AddAnimalImageParams) (AnimalImage, error) {
	row := q.db.QueryRow(ctx, addAnimalImage,
		arg.AnimalID,
		arg.StorageKey,
		arg.AltText,
		arg.Position,
	)
	var i AnimalImage
	err := row.Scan(
		&i.ID,
		&i.AnimalID,
		&i.StorageKey,
		&i.AltText,
		&i.Position,
		&i.ModerationStatus,
		&i.ModeratedBy,
		&i.ModeratedAt,
		&i.RemovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const assignAnimalOrganization = `-- name: AssignAnimalOrganization :one
UPDATE animals
SET responsible_organization_id = $1
WHERE id = $2
  AND source = 'private_submission'
  AND status = 'pending_organization'
  AND organization_review_status IN ('pending', 'changes_requested')
  AND deleted_at IS NULL
RETURNING id, submitted_by, responsible_organization_id, source, status, organization_review_status, organization_review_notes, reviewed_by, reviewed_at, name, species, breed, sex, size, birth_date, approximate_age_months, description, health_notes, behavior_notes, vaccinated, neutered, special_needs, city, state_code, country_code, latitude, longitude, published_at, unavailable_reason, adopted_at, deleted_at, created_at, updated_at
`

type AssignAnimalOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	ID             pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) AssignAnimalOrganization(ctx context.Context, arg AssignAnimalOrganizationParams) (Animal, error) {
	row := q.db.QueryRow(ctx, assignAnimalOrganization, arg.OrganizationID, arg.ID)
	var i Animal
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.ResponsibleOrganizationID,
		&i.Source,
		&i.Status,
		&i.OrganizationReviewStatus,
		&i.OrganizationReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.Size,
		&i.BirthDate,
		&i.ApproximateAgeMonths,
		&i.Description,
		&i.HealthNotes,
		&i.BehaviorNotes,
		&i.Vaccinated,
		&i.Neutered,
		&i.SpecialNeeds,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.PublishedAt,
		&i.UnavailableReason,
		&i.AdoptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationAnimal = `-- name: CreateOrganizationAnimal :one
INSERT INTO animals (
    submitted_by, responsible_organization_id, source, status,
    organization_review_status, reviewed_by, reviewed_at, name, species,
    breed, sex, size, birth_date, approximate_age_months, description,
    health_notes, behavior_notes, vaccinated, neutered, special_needs,
    city, state_code, country_code, latitude, longitude, published_at
) VALUES (
    $1, $2, 'organization',
    'available', 'accepted', $1, now(), $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20, now()
)
RETURNING id, submitted_by, responsible_organization_id, source, status, organization_review_status, organization_review_notes, reviewed_by, reviewed_at, name, species, breed, sex, size, birth_date, approximate_age_months, description, health_notes, behavior_notes, vaccinated, neutered, special_needs, city, state_code, country_code, latitude, longitude, published_at, unavailable_reason, adopted_at, deleted_at, created_at, updated_at
`

type CreateOrganizationAnimalParams struct {
	SubmittedBy               pgtype.UUID    `db:"submitted_by" json:"submitted_by"`
	ResponsibleOrganizationID pgtype.UUID    `db:"responsible_organization_id" json:"responsible_organization_id"`
	Name                      string         `db:"name" json:"name"`
	Species                   string         `db:"species" json:"species"`
	Breed                     *string        `db:"breed" json:"breed"`
	Sex                       string         `db:"sex" json:"sex"`
	Size                      string         `db:"size" json:"size"`
	BirthDate                 pgtype.Date    `db:"birth_date" json:"birth_date"`
	ApproximateAgeMonths      *int32         `db:"approximate_age_months" json:"approximate_age_months"`
	Description               string         `db:"description" json:"description"`
	HealthNotes               string         `db:"health_notes" json:"health_notes"`
	BehaviorNotes             string         `db:"behavior_notes" json:"behavior_notes"`
	Vaccinated                *bool          `db:"vaccinated" json:"vaccinated"`
	Neutered                  *bool          `db:"neutered" json:"neutered"`
	SpecialNeeds              bool           `db:"special_needs" json:"special_needs"`
	City                      string         `db:"city" json:"city"`
	StateCode                 string         `db:"state_code" json:"state_code"`
	CountryCode               string         `db:"country_code" json:"country_code"`
	Latitude                  pgtype.Numeric `db:"latitude" json:"latitude"`
	Longitude                 pgtype.Numeric `db:"longitude" json:"longitude"`
}

func (q *Queries) CreateOrganizationAnimal(ctx context.Context, arg CreateOrganizationAnimalParams) (Animal, error) {
	row := q.db.QueryRow(ctx, createOrganizationAnimal,
		arg.SubmittedBy,
		arg.ResponsibleOrganizationID,
		arg.Name,
		arg.Species,
		arg.Breed,
		arg.Sex,
		arg.Size,
		arg.BirthDate,
		arg.ApproximateAgeMonths,
		arg.Description,
		arg.HealthNotes,
		arg.BehaviorNotes,
		arg.Vaccinated,
		arg.Neutered,
		arg.SpecialNeeds,
		arg.City,
		arg.StateCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
	)
	var i Animal
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.ResponsibleOrganizationID,
		&i.Source,
		&i.Status,
		&i.OrganizationReviewStatus,
		&i.OrganizationReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.Size,
		&i.BirthDate,
		&i.ApproximateAgeMonths,
		&i.Description,
		&i.HealthNotes,
		&i.BehaviorNotes,
		&i.Vaccinated,
		&i.Neutered,
		&i.SpecialNeeds,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.PublishedAt,
		&i.UnavailableReason,
		&i.AdoptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPrivateAnimal = `-- name: CreatePrivateAnimal :one
INSERT INTO animals (
    submitted_by, responsible_organization_id, source, name, species, breed,
    sex, size, birth_date, approximate_age_months, description, health_notes,
    behavior_notes, vaccinated, neutered, special_needs, city, state_code,
    country_code, latitude, longitude
) VALUES (
    $1, $2, 'private_submission',
    $3, $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20
)
RETURNING id, submitted_by, responsible_organization_id, source, status, organization_review_status, organization_review_notes, reviewed_by, reviewed_at, name, species, breed, sex, size, birth_date, approximate_age_months, description, health_notes, behavior_notes, vaccinated, neutered, special_needs, city, state_code, country_code, latitude, longitude, published_at, unavailable_reason, adopted_at, deleted_at, created_at, updated_at
`

type CreatePrivateAnimalParams struct {
	SubmittedBy               pgtype.UUID    `db:"submitted_by" json:"submitted_by"`
	ResponsibleOrganizationID pgtype.UUID    `db:"responsible_organization_id" json:"responsible_organization_id"`
	Name                      string         `db:"name" json:"name"`
	Species                   string         `db:"species" json:"species"`
	Breed                     *string        `db:"breed" json:"breed"`
	Sex                       string         `db:"sex" json:"sex"`
	Size                      string         `db:"size" json:"size"`
	BirthDate                 pgtype.Date    `db:"birth_date" json:"birth_date"`
	ApproximateAgeMonths      *int32         `db:"approximate_age_months" json:"approximate_age_months"`
	Description               string         `db:"description" json:"description"`
	HealthNotes               string         `db:"health_notes" json:"health_notes"`
	BehaviorNotes             string         `db:"behavior_notes" json:"behavior_notes"`
	Vaccinated                *bool          `db:"vaccinated" json:"vaccinated"`
	Neutered                  *bool          `db:"neutered" json:"neutered"`
	SpecialNeeds              bool           `db:"special_needs" json:"special_needs"`
	City                      string         `db:"city" json:"city"`
	StateCode                 string         `db:"state_code" json:"state_code"`
	CountryCode               string         `db:"country_code" json:"country_code"`
	Latitude                  pgtype.Numeric `db:"latitude" json:"latitude"`
	Longitude                 pgtype.Numeric `db:"longitude" json:"longitude"`
}

func (q *Queries) CreatePrivateAnimal(ctx context.Context, arg CreatePrivateAnimalParams) (Animal, error) {
	row := q.db.QueryRow(ctx, createPrivateAnimal,
		arg.SubmittedBy,
		arg.ResponsibleOrganizationID,
		arg.Name,
		arg.Species,
		arg.Breed,
		arg.Sex,
		arg.Size,
		arg.BirthDate,
		arg.ApproximateAgeMonths,
		arg.Description,
		arg.HealthNotes,
		arg.BehaviorNotes,
		arg.Vaccinated,
		arg.Neutered,
		arg.SpecialNeeds,
		arg.City,
		arg.StateCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
	)
	var i Animal
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.ResponsibleOrganizationID,
		&i.Source,
		&i.Status,
		&i.OrganizationReviewStatus,
		&i.OrganizationReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.Size,
		&i.BirthDate,
		&i.ApproximateAgeMonths,
		&i.Description,
		&i.HealthNotes,
		&i.BehaviorNotes,
		&i.Vaccinated,
		&i.Neutered,
		&i.SpecialNeeds,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.PublishedAt,
		&i.UnavailableReason,
		&i.AdoptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnimalByID = `-- name: GetAnimalByID :one
SELECT id, submitted_by, responsible_organization_id, source, status, organization_review_status, organization_review_notes, reviewed_by, reviewed_at, name, species, breed, sex, size, birth_date, approximate_age_months, description, health_notes, behavior_notes, vaccinated, neutered, special_needs, city, state_code, country_code, latitude, longitude, published_at, unavailable_reason, adopted_at, deleted_at, created_at, updated_at FROM animals WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnimalByID(ctx context.Context, id pgtype.UUID) (Animal, error) {
	row := q.db.QueryRow(ctx, getAnimalByID, id)
	var i Animal
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.ResponsibleOrganizationID,
		&i.Source,
		&i.Status,
		&i.OrganizationReviewStatus,
		&i.OrganizationReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.Size,
		&i.BirthDate,
		&i.ApproximateAgeMonths,
		&i.Description,
		&i.HealthNotes,
		&i.BehaviorNotes,
		&i.Vaccinated,
		&i.Neutered,
		&i.SpecialNeeds,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.PublishedAt,
		&i.UnavailableReason,
		&i.AdoptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnimalWithOrganization = `-- name: GetAnimalWithOrganization :one
SELECT a.id, a.submitted_by, a.responsible_organization_id, a.source, a.status, a.organization_review_status, a.organization_review_notes, a.reviewed_by, a.reviewed_at, a.name, a.species, a.breed, a.sex, a.size, a.birth_date, a.approximate_age_months, a.description, a.health_notes, a.behavior_notes, a.vaccinated, a.neutered, a.special_needs, a.city, a.state_code, a.country_code, a.latitude, a.longitude, a.published_at, a.unavailable_reason, a.adopted_at, a.deleted_at, a.created_at, a.updated_at, o.display_name AS organization_name, o.slug AS organization_slug,
       o.verification_status AS organization_verification_status
FROM animals a
LEFT JOIN organizations o ON o.id = a.responsible_organization_id
WHERE a.id = $1 AND a.deleted_at IS NULL
`

type GetAnimalWithOrganizationRow struct {
	ID                             pgtype.UUID        `db:"id" json:"id"`
	SubmittedBy                    pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	ResponsibleOrganizationID      pgtype.UUID        `db:"responsible_organization_id" json:"responsible_organization_id"`
	Source                         string             `db:"source" json:"source"`
	Status                         string             `db:"status" json:"status"`
	OrganizationReviewStatus       string             `db:"organization_review_status" json:"organization_review_status"`
	OrganizationReviewNotes        *string            `db:"organization_review_notes" json:"organization_review_notes"`
	ReviewedBy                     pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt                     pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	Name                           string             `db:"name" json:"name"`
	Species                        string             `db:"species" json:"species"`
	Breed                          *string            `db:"breed" json:"breed"`
	Sex                            string             `db:"sex" json:"sex"`
	Size                           string             `db:"size" json:"size"`
	BirthDate                      pgtype.Date        `db:"birth_date" json:"birth_date"`
	ApproximateAgeMonths           *int32             `db:"approximate_age_months" json:"approximate_age_months"`
	Description                    string             `db:"description" json:"description"`
	HealthNotes                    string             `db:"health_notes" json:"health_notes"`
	BehaviorNotes                  string             `db:"behavior_notes" json:"behavior_notes"`
	Vaccinated                     *bool              `db:"vaccinated" json:"vaccinated"`
	Neutered                       *bool              `db:"neutered" json:"neutered"`
	SpecialNeeds                   bool               `db:"special_needs" json:"special_needs"`
	City                           string             `db:"city" json:"city"`
	StateCode                      string             `db:"state_code" json:"state_code"`
	CountryCode                    string             `db:"country_code" json:"country_code"`
	Latitude                       pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude                      pgtype.Numeric     `db:"longitude" json:"longitude"`
	PublishedAt                    pgtype.Timestamptz `db:"published_at" json:"published_at"`
	UnavailableReason              *string            `db:"unavailable_reason" json:"unavailable_reason"`
	AdoptedAt                      pgtype.Timestamptz `db:"adopted_at" json:"adopted_at"`
	DeletedAt                      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt                      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OrganizationName               *string            `db:"organization_name" json:"organization_name"`
	OrganizationSlug               *string            `db:"organization_slug" json:"organization_slug"`
	OrganizationVerificationStatus *string            `db:"organization_verification_status" json:"organization_verification_status"`
}

func (q *Queries) GetAnimalWithOrganization(ctx context.Context, id pgtype.UUID) (GetAnimalWithOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getAnimalWithOrganization, id)
	var i GetAnimalWithOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.ResponsibleOrganizationID,
		&i.Source,
		&i.Status,
		&i.OrganizationReviewStatus,
		&i.OrganizationReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.Size,
		&i.BirthDate,
		&i.ApproximateAgeMonths,
		&i.Description,
		&i.HealthNotes,
		&i.BehaviorNotes,
		&i.Vaccinated,
		&i.Neutered,
		&i.SpecialNeeds,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.PublishedAt,
		&i.UnavailableReason,
		&i.AdoptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationName,
		&i.OrganizationSlug,
		&i.OrganizationVerificationStatus,
	)
	return i, err
}

const listAnimalImages = `-- name: ListAnimalImages :many
SELECT id, animal_id, storage_key, alt_text, position, moderation_status, moderated_by, moderated_at, removed_at, created_at FROM animal_images
WHERE animal_id = $1
  AND removed_at IS NULL
  AND ($2::boolean OR moderation_status = 'approved')
ORDER BY position, created_at, id
`

type ListAnimalImagesParams struct {
	AnimalID       pgtype.UUID `db:"animal_id" json:"animal_id"`
	IncludePending bool        `db:"include_pending" json:"include_pending"`
}

func (q *Queries) ListAnimalImages(ctx context.Context, arg ListAnimalImagesParams) ([]AnimalImage, error) {
	rows, err := q.db.Query(ctx, listAnimalImages, arg.AnimalID, arg.IncludePending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnimalImage{}
	for rows.Next() {
		var i AnimalImage
		if err := rows.Scan(
			&i.ID,
			&i.AnimalID,
			&i.StorageKey,
			&i.AltText,
			&i.Position,
			&i.ModerationStatus,
			&i.ModeratedBy,
			&i.ModeratedAt,
			&i.RemovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnimalsByOrganization = `-- name: ListAnimalsByOrganization :many
SELECT id, submitted_by, responsible_organization_id, source, status, organization_review_status, organization_review_notes, reviewed_by, reviewed_at, name, species, breed, sex, size, birth_date, approximate_age_months, description, health_notes, behavior_notes, vaccinated, neutered, special_needs, city, state_code, country_code, latitude, longitude, published_at, unavailable_reason, adopted_at, deleted_at, created_at, updated_at FROM animals
WHERE responsible_organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC, id
LIMIT $4::int OFFSET $3::int
`

type ListAnimalsByOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Status         *string     `db:"status" json:"status"`
	PageOffset     int32       `db:"page_offset" json:"page_offset"`
	PageSize       int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListAnimalsByOrganization(ctx context.Context, arg ListAnimalsByOrganizationParams) ([]Animal, error) {
	rows, err := q.db.Query(ctx, listAnimalsByOrganization,
		arg.OrganizationID,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Animal{}
	for rows.Next() {
		var i Animal
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.ResponsibleOrganizationID,
			&i.Source,
			&i.Status,
			&i.OrganizationReviewStatus,
			&i.OrganizationReviewNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Name,
			&i.Species,
			&i.Breed,
			&i.Sex,
			&i.Size,
			&i.BirthDate,
			&i.ApproximateAgeMonths,
			&i.Description,
			&i.HealthNotes,
			&i.BehaviorNotes,
			&i.Vaccinated,
			&i.Neutered,
			&i.SpecialNeeds,
			&i.City,
			&i.StateCode,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.PublishedAt,
			&i.UnavailableReason,
			&i.AdoptedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnimalsBySubmitter = `-- name: ListAnimalsBySubmitter :many
SELECT id, submitted_by, responsible_organization_id, source, status, organization_review_status, organization_review_notes, reviewed_by, reviewed_at, name, species, breed, sex, size, birth_date, approximate_age_months, description, health_notes, behavior_notes, vaccinated, neutered, special_needs, city, state_code, country_code, latitude, longitude, published_at, unavailable_reason, adopted_at, deleted_at, created_at, updated_at FROM animals
WHERE submitted_by = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id
LIMIT $3::int OFFSET $2::int
`

type ListAnimalsBySubmitterParams struct {
	SubmittedBy pgtype.UUID `db:"submitted_by" json:"submitted_by"`
	PageOffset  int32       `db:"page_offset" json:"page_offset"`
	PageSize    int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListAnimalsBySubmitter(ctx context.Context, arg ListAnimalsBySubmitterParams) ([]Animal, error) {
	rows, err := q.db.Query(ctx, listAnimalsBySubmitter, arg.SubmittedBy, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Animal{}
	for rows.Next() {
		var i Animal
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.ResponsibleOrganizationID,
			&i.Source,
			&i.Status,
			&i.OrganizationReviewStatus,
			&i.OrganizationReviewNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Name,
			&i.Species,
			&i.Breed,
			&i.Sex,
			&i.Size,
			&i.BirthDate,
			&i.ApproximateAgeMonths,
			&i.Description,
			&i.HealthNotes,
			&i.BehaviorNotes,
			&i.Vaccinated,
			&i.Neutered,
			&i.SpecialNeeds,
			&i.City,
			&i.StateCode,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.PublishedAt,
			&i.UnavailableReason,
			&i.AdoptedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableAnimals = `-- name: ListAvailableAnimals :many
SELECT a.id, a.submitted_by, a.responsible_organization_id, a.source, a.status, a.organization_review_status, a.organization_review_notes, a.reviewed_by, a.reviewed_at, a.name, a.species, a.breed, a.sex, a.size, a.birth_date, a.approximate_age_months, a.description, a.health_notes, a.behavior_notes, a.vaccinated, a.neutered, a.special_needs, a.city, a.state_code, a.country_code, a.latitude, a.longitude, a.published_at, a.unavailable_reason, a.adopted_at, a.deleted_at, a.created_at, a.updated_at, o.display_name AS organization_name, o.slug AS organization_slug,
       CASE
           WHEN $1::numeric IS NULL
             OR $2::numeric IS NULL
             OR a.latitude IS NULL OR a.longitude IS NULL THEN NULL
           ELSE power(a.latitude - $1, 2)
              + power(a.longitude - $2, 2)
       END AS distance_score
FROM animals a
JOIN organizations o ON o.id = a.responsible_organization_id
WHERE a.status = 'available'
  AND a.deleted_at IS NULL
  AND o.verification_status = 'verified'
  AND o.deactivated_at IS NULL
  AND ($3::text IS NULL OR a.species = $3)
  AND ($4::text IS NULL OR a.size = $4)
  AND ($5::text IS NULL OR a.state_code = $5)
  AND ($6::text IS NULL OR a.city = $6)
  AND NOT EXISTS (
      SELECT 1 FROM animal_preferences p
      WHERE p.user_id = $7
        AND p.animal_id = a.id
        AND p.preference = 'not_interested'
  )
ORDER BY distance_score ASC NULLS LAST, a.published_at DESC, a.id
LIMIT $9::int OFFSET $8::int
`

type ListAvailableAnimalsParams struct {
	ViewerLatitude  pgtype.Numeric `db:"viewer_latitude" json:"viewer_latitude"`
	ViewerLongitude pgtype.Numeric `db:"viewer_longitude" json:"viewer_longitude"`
	Species         *string        `db:"species" json:"species"`
	Size            *string        `db:"size" json:"size"`
	StateCode       *string        `db:"state_code" json:"state_code"`
	City            *string        `db:"city" json:"city"`
	ViewerID        pgtype.UUID    `db:"viewer_id" json:"viewer_id"`
	PageOffset      int32          `db:"page_offset" json:"page_offset"`
	PageSize        int32          `db:"page_size" json:"page_size"`
}

type ListAvailableAnimalsRow struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	SubmittedBy               pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	ResponsibleOrganizationID pgtype.UUID        `db:"responsible_organization_id" json:"responsible_organization_id"`
	Source                    string             `db:"source" json:"source"`
	Status                    string             `db:"status" json:"status"`
	OrganizationReviewStatus  string             `db:"organization_review_status" json:"organization_review_status"`
	OrganizationReviewNotes   *string            `db:"organization_review_notes" json:"organization_review_notes"`
	ReviewedBy                pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt                pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	Name                      string             `db:"name" json:"name"`
	Species                   string             `db:"species" json:"species"`
	Breed                     *string            `db:"breed" json:"breed"`
	Sex                       string             `db:"sex" json:"sex"`
	Size                      string             `db:"size" json:"size"`
	BirthDate                 pgtype.Date        `db:"birth_date" json:"birth_date"`
	ApproximateAgeMonths      *int32             `db:"approximate_age_months" json:"approximate_age_months"`
	Description               string             `db:"description" json:"description"`
	HealthNotes               string             `db:"health_notes" json:"health_notes"`
	BehaviorNotes             string             `db:"behavior_notes" json:"behavior_notes"`
	Vaccinated                *bool              `db:"vaccinated" json:"vaccinated"`
	Neutered                  *bool              `db:"neutered" json:"neutered"`
	SpecialNeeds              bool               `db:"special_needs" json:"special_needs"`
	City                      string             `db:"city" json:"city"`
	StateCode                 string             `db:"state_code" json:"state_code"`
	CountryCode               string             `db:"country_code" json:"country_code"`
	Latitude                  pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude                 pgtype.Numeric     `db:"longitude" json:"longitude"`
	PublishedAt               pgtype.Timestamptz `db:"published_at" json:"published_at"`
	UnavailableReason         *string            `db:"unavailable_reason" json:"unavailable_reason"`
	AdoptedAt                 pgtype.Timestamptz `db:"adopted_at" json:"adopted_at"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OrganizationName          string             `db:"organization_name" json:"organization_name"`
	OrganizationSlug          string             `db:"organization_slug" json:"organization_slug"`
	DistanceScore             interface{}        `db:"distance_score" json:"distance_score"`
}

func (q *Queries) ListAvailableAnimals(ctx context.Context, arg ListAvailableAnimalsParams) ([]ListAvailableAnimalsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableAnimals,
		arg.ViewerLatitude,
		arg.ViewerLongitude,
		arg.Species,
		arg.Size,
		arg.StateCode,
		arg.City,
		arg.ViewerID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableAnimalsRow{}
	for rows.Next() {
		var i ListAvailableAnimalsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.ResponsibleOrganizationID,
			&i.Source,
			&i.Status,
			&i.OrganizationReviewStatus,
			&i.OrganizationReviewNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Name,
			&i.Species,
			&i.Breed,
			&i.Sex,
			&i.Size,
			&i.BirthDate,
			&i.ApproximateAgeMonths,
			&i.Description,
			&i.HealthNotes,
			&i.BehaviorNotes,
			&i.Vaccinated,
			&i.Neutered,
			&i.SpecialNeeds,
			&i.City,
			&i.StateCode,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.PublishedAt,
			&i.UnavailableReason,
			&i.AdoptedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.DistanceScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderateAnimalImage = `-- name: ModerateAnimalImage :one
UPDATE animal_images
SET moderation_status = $1,
    moderated_by = $2,
    moderated_at = now()
WHERE id = $3 AND removed_at IS NULL
RETURNING id, animal_id, storage_key, alt_text, position, moderation_status, moderated_by, moderated_at, removed_at, created_at
`

type ModerateAnimalImageParams struct {
	ModerationStatus string      `db:"moderation_status" json:"moderation_status"`
	ModeratedBy      pgtype.UUID `db:"moderated_by" json:"moderated_by"`
	ID               pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ModerateAnimalImage(ctx context.Context, arg ModerateAnimalImageParams) (AnimalImage, error) {
	row := q.db.QueryRow(ctx, moderateAnimalImage, arg.ModerationStatus, arg.ModeratedBy, arg.ID)
	var i AnimalImage
	err := row.Scan(
		&i.ID,
		&i.AnimalID,
		&i.StorageKey,
		&i.AltText,
		&i.Position,
		&i.ModerationStatus,
		&i.ModeratedBy,
		&i.ModeratedAt,
		&i.RemovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const removeAnimalImage = `-- name: RemoveAnimalImage :execrows
UPDATE animal_images
SET removed_at = now()
WHERE id = $1 AND animal_id = $2 AND removed_at IS NULL
`

type RemoveAnimalImageParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	AnimalID pgtype.UUID `db:"animal_id" json:"animal_id"`
}

func (q *Queries) RemoveAnimalImage(ctx context.Context, arg RemoveAnimalImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeAnimalImage, arg.ID, arg.AnimalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviewAnimalSubmission = `-- name: ReviewAnimalSubmission :one
UPDATE animals
SET organization_review_status = $1,
    organization_review_notes = $2,
    reviewed_by = $3,
    reviewed_at = now(),
    status = CASE
        WHEN $1::text = 'accepted' THEN 'available'
        ELSE 'pending_organization'
    END,
    published_at = CASE WHEN $1::text = 'accepted' THEN now() ELSE NULL END
WHERE id = $4
  AND responsible_organization_id = $5
  AND source = 'private_submission'
  AND status = 'pending_organization'
  AND deleted_at IS NULL
RETURNING id, submitted_by, responsible_organization_id, source, status, organization_review_status, organization_review_notes, reviewed_by, reviewed_at, name, species, breed, sex, size, birth_date, approximate_age_months, description, health_notes, behavior_notes, vaccinated, neutered, special_needs, city, state_code, country_code, latitude, longitude, published_at, unavailable_reason, adopted_at, deleted_at, created_at, updated_at
`

type ReviewAnimalSubmissionParams struct {
	ReviewStatus   string      `db:"review_status" json:"review_status"`
	ReviewNotes    *string     `db:"review_notes" json:"review_notes"`
	ReviewedBy     pgtype.UUID `db:"reviewed_by" json:"reviewed_by"`
	ID             pgtype.UUID `db:"id" json:"id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ReviewAnimalSubmission(ctx context.Context, arg ReviewAnimalSubmissionParams) (Animal, error) {
	row := q.db.QueryRow(ctx, reviewAnimalSubmission,
		arg.ReviewStatus,
		arg.ReviewNotes,
		arg.ReviewedBy,
		arg.ID,
		arg.OrganizationID,
	)
	var i Animal
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.ResponsibleOrganizationID,
		&i.Source,
		&i.Status,
		&i.OrganizationReviewStatus,
		&i.OrganizationReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.Size,
		&i.BirthDate,
		&i.ApproximateAgeMonths,
		&i.Description,
		&i.HealthNotes,
		&i.BehaviorNotes,
		&i.Vaccinated,
		&i.Neutered,
		&i.SpecialNeeds,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.PublishedAt,
		&i.UnavailableReason,
		&i.AdoptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAnimalStatus = `-- name: SetAnimalStatus :one
UPDATE animals
SET status = $1,
    unavailable_reason = CASE
        WHEN $1::text IN ('unavailable', 'under_review') THEN $2
        ELSE unavailable_reason
    END,
    adopted_at = CASE WHEN $1::text = 'adopted' THEN now() ELSE adopted_at END
WHERE id = $3
  AND responsible_organization_id = $4
  AND deleted_at IS NULL
RETURNING id, submitted_by, responsible_organization_id, source, status, organization_review_status, organization_review_notes, reviewed_by, reviewed_at, name, species, breed, sex, size, birth_date, approximate_age_months, description, health_notes, behavior_notes, vaccinated, neutered, special_needs, city, state_code, country_code, latitude, longitude, published_at, unavailable_reason, adopted_at, deleted_at, created_at, updated_at
`

type SetAnimalStatusParams struct {
	Status         string      `db:"status" json:"status"`
	Reason         *string     `db:"reason" json:"reason"`
	ID             pgtype.UUID `db:"id" json:"id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetAnimalStatus(ctx context.Context, arg SetAnimalStatusParams) (Animal, error) {
	row := q.db.QueryRow(ctx, setAnimalStatus,
		arg.Status,
		arg.Reason,
		arg.ID,
		arg.OrganizationID,
	)
	var i Animal
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.ResponsibleOrganizationID,
		&i.Source,
		&i.Status,
		&i.OrganizationReviewStatus,
		&i.OrganizationReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.Size,
		&i.BirthDate,
		&i.ApproximateAgeMonths,
		&i.Description,
		&i.HealthNotes,
		&i.BehaviorNotes,
		&i.Vaccinated,
		&i.Neutered,
		&i.SpecialNeeds,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.PublishedAt,
		&i.UnavailableReason,
		&i.AdoptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteAnimal = `-- name: SoftDeleteAnimal :execrows
UPDATE animals
SET deleted_at = now()
WHERE id = $1 AND submitted_by = $2 AND deleted_at IS NULL
`

type SoftDeleteAnimalParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	SubmittedBy pgtype.UUID `db:"submitted_by" json:"submitted_by"`
}

func (q *Queries) SoftDeleteAnimal(ctx context.Context, arg SoftDeleteAnimalParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAnimal, arg.ID, arg.SubmittedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnimalDetails = `-- name: UpdateAnimalDetails :one
UPDATE animals
SET name = $1, species = $2, breed = $3,
    sex = $4, size = $5, birth_date = $6,
    approximate_age_months = $7,
    description = $8, health_notes = $9,
    behavior_notes = $10, vaccinated = $11,
    neutered = $12, special_needs = $13,
    city = $14, state_code = $15,
    country_code = $16, latitude = $17,
    longitude = $18
WHERE id = $19 AND deleted_at IS NULL AND status <> 'adopted'
RETURNING id, submitted_by, responsible_organization_id, source, status, organization_review_status, organization_review_notes, reviewed_by, reviewed_at, name, species, breed, sex, size, birth_date, approximate_age_months, description, health_notes, behavior_notes, vaccinated, neutered, special_needs, city, state_code, country_code, latitude, longitude, published_at, unavailable_reason, adopted_at, deleted_at, created_at, updated_at
`

type UpdateAnimalDetailsParams struct {
	Name                 string         `db:"name" json:"name"`
	Species              string         `db:"species" json:"species"`
	Breed                *string        `db:"breed" json:"breed"`
	Sex                  string         `db:"sex" json:"sex"`
	Size                 string         `db:"size" json:"size"`
	BirthDate            pgtype.Date    `db:"birth_date" json:"birth_date"`
	ApproximateAgeMonths *int32         `db:"approximate_age_months" json:"approximate_age_months"`
	Description          string         `db:"description" json:"description"`
	HealthNotes          string         `db:"health_notes" json:"health_notes"`
	BehaviorNotes        string         `db:"behavior_notes" json:"behavior_notes"`
	Vaccinated           *bool          `db:"vaccinated" json:"vaccinated"`
	Neutered             *bool          `db:"neutered" json:"neutered"`
	SpecialNeeds         bool           `db:"special_needs" json:"special_needs"`
	City                 string         `db:"city" json:"city"`
	StateCode            string         `db:"state_code" json:"state_code"`
	CountryCode          string         `db:"country_code" json:"country_code"`
	Latitude             pgtype.Numeric `db:"latitude" json:"latitude"`
	Longitude            pgtype.Numeric `db:"longitude" json:"longitude"`
	ID                   pgtype.UUID    `db:"id" json:"id"`
}

func (q *Queries) UpdateAnimalDetails(ctx context.Context, arg UpdateAnimalDetailsParams) (Animal, error) {
	row := q.db.QueryRow(ctx, updateAnimalDetails,
		arg.Name,
		arg.Species,
		arg.Breed,
		arg.Sex,
		arg.Size,
		arg.BirthDate,
		arg.ApproximateAgeMonths,
		arg.Description,
		arg.HealthNotes,
		arg.BehaviorNotes,
		arg.Vaccinated,
		arg.Neutered,
		arg.SpecialNeeds,
		arg.City,
		arg.StateCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.ID,
	)
	var i Animal
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.ResponsibleOrganizationID,
		&i.Source,
		&i.Status,
		&i.OrganizationReviewStatus,
		&i.OrganizationReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.Size,
		&i.BirthDate,
		&i.ApproximateAgeMonths,
		&i.Description,
		&i.HealthNotes,
		&i.BehaviorNotes,
		&i.Vaccinated,
		&i.Neutered,
		&i.SpecialNeeds,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.PublishedAt,
		&i.UnavailableReason,
		&i.AdoptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
