// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addApplicationStatusHistory = `-- name: AddApplicationStatusHistory :one
INSERT INTO application_status_history (
    application_id, from_status, to_status, reason, changed_by
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING id, application_id, from_status, to_status, reason, changed_by, created_at
`

type AddApplicationStatusHistoryParams struct {
	ApplicationID pgtype.UUID `db:"application_id" json:"application_id"`
	FromStatus    *string     `db:"from_status" json:"from_status"`
	ToStatus      string      `db:"to_status" json:"to_status"`
	Reason        *string     `db:"reason" json:"reason"`
	ChangedBy     pgtype.UUID `db:"changed_by" json:"changed_by"`
}

func (q *Queries) AddApplicationStatusHistory(ctx context.Context, arg AddApplicationStatusHistoryParams) (ApplicationStatusHistory, error) {
	row := q.db.QueryRow(ctx, addApplicationStatusHistory,
		arg.ApplicationID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.ChangedBy,
	)
	var i ApplicationStatusHistory
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Reason,
		&i.ChangedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createAdoptionApplication = `-- name: CreateAdoptionApplication :one
INSERT INTO adoption_applications (
    animal_id, adopter_id, organization_id, applicant_message
)
SELECT a.id, $1, a.responsible_organization_id, $2
FROM animals a
WHERE a.id = $3
  AND a.status = 'available'
  AND a.deleted_at IS NULL
  AND EXISTS (
      SELECT 1 FROM animal_preferences p
      WHERE p.user_id = $1
        AND p.animal_id = a.id
        AND p.preference = 'liked'
  )
RETURNING id, animal_id, adopter_id, organization_id, status, applicant_message, decision_reason, decided_by, decided_at, withdrawn_at, completed_at, created_at, updated_at
`

type CreateAdoptionApplicationParams struct {
	AdopterID        pgtype.UUID `db:"adopter_id" json:"adopter_id"`
	ApplicantMessage string      `db:"applicant_message" json:"applicant_message"`
	AnimalID         pgtype.UUID `db:"animal_id" json:"animal_id"`
}

func (q *Queries) CreateAdoptionApplication(ctx context.Context, arg CreateAdoptionApplicationParams) (AdoptionApplication, error) {
	row := q.db.QueryRow(ctx, createAdoptionApplication, arg.AdopterID, arg.ApplicantMessage, arg.AnimalID)
	var i AdoptionApplication
	err := row.Scan(
		&i.ID,
		&i.AnimalID,
		&i.AdopterID,
		&i.OrganizationID,
		&i.Status,
		&i.ApplicantMessage,
		&i.DecisionReason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.WithdrawnAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApplicationScreening = `-- name: CreateApplicationScreening :one
INSERT INTO application_screenings (
    application_id, version, questions, requested_by
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, application_id, version, questions, answers, status, requested_by, submitted_at, reviewed_by, reviewed_at, outcome, private_notes, created_at, updated_at
`

type CreateApplicationScreeningParams struct {
	ApplicationID pgtype.UUID `db:"application_id" json:"application_id"`
	Version       int32       `db:"version" json:"version"`
	Questions     []byte      `db:"questions" json:"questions"`
	RequestedBy   pgtype.UUID `db:"requested_by" json:"requested_by"`
}

func (q *Queries) CreateApplicationScreening(ctx context.Context, arg CreateApplicationScreeningParams) (ApplicationScreening, error) {
	row := q.db.QueryRow(ctx, createApplicationScreening,
		arg.ApplicationID,
		arg.Version,
		arg.Questions,
		arg.RequestedBy,
	)
	var i ApplicationScreening
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.Questions,
		&i.Answers,
		&i.Status,
		&i.RequestedBy,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Outcome,
		&i.PrivateNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPostAdoptionFollowup = `-- name: CreatePostAdoptionFollowup :one
INSERT INTO post_adoption_followups (
    application_id, organization_id, occurred_at, contact_method,
    notes, welfare_status, recorded_by
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7
)
RETURNING id, application_id, organization_id, occurred_at, contact_method, notes, welfare_status, recorded_by, created_at
`

type CreatePostAdoptionFollowupParams struct {
	ApplicationID  pgtype.UUID        `db:"application_id" json:"application_id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ContactMethod  string             `db:"contact_method" json:"contact_method"`
	Notes          string             `db:"notes" json:"notes"`
	WelfareStatus  string             `db:"welfare_status" json:"welfare_status"`
	RecordedBy     pgtype.UUID        `db:"recorded_by" json:"recorded_by"`
}

func (q *Queries) CreatePostAdoptionFollowup(ctx context.Context, arg CreatePostAdoptionFollowupParams) (PostAdoptionFollowup, error) {
	row := q.db.QueryRow(ctx, createPostAdoptionFollowup,
		arg.ApplicationID,
		arg.OrganizationID,
		arg.OccurredAt,
		arg.ContactMethod,
		arg.Notes,
		arg.WelfareStatus,
		arg.RecordedBy,
	)
	var i PostAdoptionFollowup
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OrganizationID,
		&i.OccurredAt,
		&i.ContactMethod,
		&i.Notes,
		&i.WelfareStatus,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAdoptionApplicationByID = `-- name: GetAdoptionApplicationByID :one
SELECT aa.id, aa.animal_id, aa.adopter_id, aa.organization_id, aa.status, aa.applicant_message, aa.decision_reason, aa.decided_by, aa.decided_at, aa.withdrawn_at, aa.completed_at, aa.created_at, aa.updated_at, a.name AS animal_name, a.status AS animal_status,
       u.display_name AS adopter_name, u.email AS adopter_email,
       o.display_name AS organization_name
FROM adoption_applications aa
JOIN animals a ON a.id = aa.animal_id
JOIN users u ON u.id = aa.adopter_id
JOIN organizations o ON o.id = aa.organization_id
WHERE aa.id = $1
`

type GetAdoptionApplicationByIDRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	AnimalID         pgtype.UUID        `db:"animal_id" json:"animal_id"`
	AdopterID        pgtype.UUID        `db:"adopter_id" json:"adopter_id"`
	OrganizationID   pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Status           string             `db:"status" json:"status"`
	ApplicantMessage string             `db:"applicant_message" json:"applicant_message"`
	DecisionReason   *string            `db:"decision_reason" json:"decision_reason"`
	DecidedBy        pgtype.UUID        `db:"decided_by" json:"decided_by"`
	DecidedAt        pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	WithdrawnAt      pgtype.Timestamptz `db:"withdrawn_at" json:"withdrawn_at"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AnimalName       string             `db:"animal_name" json:"animal_name"`
	AnimalStatus     string             `db:"animal_status" json:"animal_status"`
	AdopterName      string             `db:"adopter_name" json:"adopter_name"`
	AdopterEmail     string             `db:"adopter_email" json:"adopter_email"`
	OrganizationName string             `db:"organization_name" json:"organization_name"`
}

func (q *Queries) GetAdoptionApplicationByID(ctx context.Context, id pgtype.UUID) (GetAdoptionApplicationByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdoptionApplicationByID, id)
	var i GetAdoptionApplicationByIDRow
	err := row.Scan(
		&i.ID,
		&i.AnimalID,
		&i.AdopterID,
		&i.OrganizationID,
		&i.Status,
		&i.ApplicantMessage,
		&i.DecisionReason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.WithdrawnAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnimalName,
		&i.AnimalStatus,
		&i.AdopterName,
		&i.AdopterEmail,
		&i.OrganizationName,
	)
	return i, err
}

const getLatestApplicationScreening = `-- name: GetLatestApplicationScreening :one
SELECT id, application_id, version, questions, answers, status, requested_by, submitted_at, reviewed_by, reviewed_at, outcome, private_notes, created_at, updated_at FROM application_screenings
WHERE application_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestApplicationScreening(ctx context.Context, applicationID pgtype.UUID) (ApplicationScreening, error) {
	row := q.db.QueryRow(ctx, getLatestApplicationScreening, applicationID)
	var i ApplicationScreening
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.Questions,
		&i.Answers,
		&i.Status,
		&i.RequestedBy,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Outcome,
		&i.PrivateNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdopterApplications = `-- name: ListAdopterApplications :many
SELECT aa.id, aa.animal_id, aa.adopter_id, aa.organization_id, aa.status, aa.applicant_message, aa.decision_reason, aa.decided_by, aa.decided_at, aa.withdrawn_at, aa.completed_at, aa.created_at, aa.updated_at, a.name AS animal_name, o.display_name AS organization_name
FROM adoption_applications aa
JOIN animals a ON a.id = aa.animal_id
JOIN organizations o ON o.id = aa.organization_id
WHERE aa.adopter_id = $1
ORDER BY aa.created_at DESC, aa.id
LIMIT $3::int OFFSET $2::int
`

type ListAdopterApplicationsParams struct {
	AdopterID  pgtype.UUID `db:"adopter_id" json:"adopter_id"`
	PageOffset int32       `db:"page_offset" json:"page_offset"`
	PageSize   int32       `db:"page_size" json:"page_size"`
}

type ListAdopterApplicationsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	AnimalID         pgtype.UUID        `db:"animal_id" json:"animal_id"`
	AdopterID        pgtype.UUID        `db:"adopter_id" json:"adopter_id"`
	OrganizationID   pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Status           string             `db:"status" json:"status"`
	ApplicantMessage string             `db:"applicant_message" json:"applicant_message"`
	DecisionReason   *string            `db:"decision_reason" json:"decision_reason"`
	DecidedBy        pgtype.UUID        `db:"decided_by" json:"decided_by"`
	DecidedAt        pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	WithdrawnAt      pgtype.Timestamptz `db:"withdrawn_at" json:"withdrawn_at"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AnimalName       string             `db:"animal_name" json:"animal_name"`
	OrganizationName string             `db:"organization_name" json:"organization_name"`
}

func (q *Queries) ListAdopterApplications(ctx context.Context, arg ListAdopterApplicationsParams) ([]ListAdopterApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listAdopterApplications, arg.AdopterID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdopterApplicationsRow{}
	for rows.Next() {
		var i ListAdopterApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AnimalID,
			&i.AdopterID,
			&i.OrganizationID,
			&i.Status,
			&i.ApplicantMessage,
			&i.DecisionReason,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.WithdrawnAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnimalName,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationStatusHistory = `-- name: ListApplicationStatusHistory :many
SELECT id, application_id, from_status, to_status, reason, changed_by, created_at FROM application_status_history
WHERE application_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListApplicationStatusHistory(ctx context.Context, applicationID pgtype.UUID) ([]ApplicationStatusHistory, error) {
	rows, err := q.db.Query(ctx, listApplicationStatusHistory, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationStatusHistory{}
	for rows.Next() {
		var i ApplicationStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.ChangedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationApplications = `-- name: ListOrganizationApplications :many
SELECT aa.id, aa.animal_id, aa.adopter_id, aa.organization_id, aa.status, aa.applicant_message, aa.decision_reason, aa.decided_by, aa.decided_at, aa.withdrawn_at, aa.completed_at, aa.created_at, aa.updated_at, a.name AS animal_name, u.display_name AS adopter_name
FROM adoption_applications aa
JOIN animals a ON a.id = aa.animal_id
JOIN users u ON u.id = aa.adopter_id
WHERE aa.organization_id = $1
  AND ($2::text IS NULL OR aa.status = $2)
  AND ($3::uuid IS NULL OR aa.animal_id = $3)
ORDER BY aa.created_at DESC, aa.id
LIMIT $5::int OFFSET $4::int
`

type ListOrganizationApplicationsParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Status         *string     `db:"status" json:"status"`
	AnimalID       pgtype.UUID `db:"animal_id" json:"animal_id"`
	PageOffset     int32       `db:"page_offset" json:"page_offset"`
	PageSize       int32       `db:"page_size" json:"page_size"`
}

type ListOrganizationApplicationsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	AnimalID         pgtype.UUID        `db:"animal_id" json:"animal_id"`
	AdopterID        pgtype.UUID        `db:"adopter_id" json:"adopter_id"`
	OrganizationID   pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Status           string             `db:"status" json:"status"`
	ApplicantMessage string             `db:"applicant_message" json:"applicant_message"`
	DecisionReason   *string            `db:"decision_reason" json:"decision_reason"`
	DecidedBy        pgtype.UUID        `db:"decided_by" json:"decided_by"`
	DecidedAt        pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	WithdrawnAt      pgtype.Timestamptz `db:"withdrawn_at" json:"withdrawn_at"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AnimalName       string             `db:"animal_name" json:"animal_name"`
	AdopterName      string             `db:"adopter_name" json:"adopter_name"`
}

func (q *Queries) ListOrganizationApplications(ctx context.Context, arg ListOrganizationApplicationsParams) ([]ListOrganizationApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationApplications,
		arg.OrganizationID,
		arg.Status,
		arg.AnimalID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationApplicationsRow{}
	for rows.Next() {
		var i ListOrganizationApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AnimalID,
			&i.AdopterID,
			&i.OrganizationID,
			&i.Status,
			&i.ApplicantMessage,
			&i.DecisionReason,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.WithdrawnAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnimalName,
			&i.AdopterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostAdoptionFollowups = `-- name: ListPostAdoptionFollowups :many
SELECT id, application_id, organization_id, occurred_at, contact_method, notes, welfare_status, recorded_by, created_at FROM post_adoption_followups
WHERE application_id = $1
ORDER BY occurred_at DESC, id
`

func (q *Queries) ListPostAdoptionFollowups(ctx context.Context, applicationID pgtype.UUID) ([]PostAdoptionFollowup, error) {
	rows, err := q.db.Query(ctx, listPostAdoptionFollowups, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostAdoptionFollowup{}
	for rows.Next() {
		var i PostAdoptionFollowup
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.OrganizationID,
			&i.OccurredAt,
			&i.ContactMethod,
			&i.Notes,
			&i.WelfareStatus,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewApplicationScreening = `-- name: ReviewApplicationScreening :one
UPDATE application_screenings
SET status = 'reviewed', reviewed_by = $1, reviewed_at = now(),
    outcome = $2, private_notes = $3
WHERE id = $4 AND status = 'submitted'
RETURNING id, application_id, version, questions, answers, status, requested_by, submitted_at, reviewed_by, reviewed_at, outcome, private_notes, created_at, updated_at
`

type ReviewApplicationScreeningParams struct {
	ReviewedBy   pgtype.UUID `db:"reviewed_by" json:"reviewed_by"`
	Outcome      *string     `db:"outcome" json:"outcome"`
	PrivateNotes *string     `db:"private_notes" json:"private_notes"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ReviewApplicationScreening(ctx context.Context, arg ReviewApplicationScreeningParams) (ApplicationScreening, error) {
	row := q.db.QueryRow(ctx, reviewApplicationScreening,
		arg.ReviewedBy,
		arg.Outcome,
		arg.PrivateNotes,
		arg.ID,
	)
	var i ApplicationScreening
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.Questions,
		&i.Answers,
		&i.Status,
		&i.RequestedBy,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Outcome,
		&i.PrivateNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setApplicationStatus = `-- name: SetApplicationStatus :one
UPDATE adoption_applications
SET status = $1,
    decision_reason = CASE
        WHEN $1::text IN ('approved', 'rejected') THEN $2
        ELSE decision_reason
    END,
    decided_by = CASE
        WHEN $1::text IN ('approved', 'rejected') THEN $3
        ELSE decided_by
    END,
    decided_at = CASE
        WHEN $1::text IN ('approved', 'rejected') THEN now()
        ELSE decided_at
    END,
    withdrawn_at = CASE WHEN $1::text = 'withdrawn' THEN now() ELSE withdrawn_at END,
    completed_at = CASE WHEN $1::text = 'completed' THEN now() ELSE completed_at END
WHERE id = $4
  AND organization_id = $5
RETURNING id, animal_id, adopter_id, organization_id, status, applicant_message, decision_reason, decided_by, decided_at, withdrawn_at, completed_at, created_at, updated_at
`

type SetApplicationStatusParams struct {
	Status         string      `db:"status" json:"status"`
	Reason         *string     `db:"reason" json:"reason"`
	ActorID        pgtype.UUID `db:"actor_id" json:"actor_id"`
	ID             pgtype.UUID `db:"id" json:"id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (AdoptionApplication, error) {
	row := q.db.QueryRow(ctx, setApplicationStatus,
		arg.Status,
		arg.Reason,
		arg.ActorID,
		arg.ID,
		arg.OrganizationID,
	)
	var i AdoptionApplication
	err := row.Scan(
		&i.ID,
		&i.AnimalID,
		&i.AdopterID,
		&i.OrganizationID,
		&i.Status,
		&i.ApplicantMessage,
		&i.DecisionReason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.WithdrawnAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitApplicationScreening = `-- name: SubmitApplicationScreening :one
UPDATE application_screenings
SET answers = $1, status = 'submitted', submitted_at = now()
WHERE id = $2 AND status = 'requested'
RETURNING id, application_id, version, questions, answers, status, requested_by, submitted_at, reviewed_by, reviewed_at, outcome, private_notes, created_at, updated_at
`

type SubmitApplicationScreeningParams struct {
	Answers []byte      `db:"answers" json:"answers"`
	ID      pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SubmitApplicationScreening(ctx context.Context, arg SubmitApplicationScreeningParams) (ApplicationScreening, error) {
	row := q.db.QueryRow(ctx, submitApplicationScreening, arg.Answers, arg.ID)
	var i ApplicationScreening
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.Questions,
		&i.Answers,
		&i.Status,
		&i.RequestedBy,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Outcome,
		&i.PrivateNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawApplication = `-- name: WithdrawApplication :one
UPDATE adoption_applications
SET status = 'withdrawn', withdrawn_at = now()
WHERE id = $1
  AND adopter_id = $2
  AND status IN ('submitted', 'screening', 'more_information_requested')
RETURNING id, animal_id, adopter_id, organization_id, status, applicant_message, decision_reason, decided_by, decided_at, withdrawn_at, completed_at, created_at, updated_at
`

type WithdrawApplicationParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	AdopterID pgtype.UUID `db:"adopter_id" json:"adopter_id"`
}

func (q *Queries) WithdrawApplication(ctx context.Context, arg WithdrawApplicationParams) (AdoptionApplication, error) {
	row := q.db.QueryRow(ctx, withdrawApplication, arg.ID, arg.AdopterID)
	var i AdoptionApplication
	err := row.Scan(
		&i.ID,
		&i.AnimalID,
		&i.AdopterID,
		&i.OrganizationID,
		&i.Status,
		&i.ApplicantMessage,
		&i.DecisionReason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.WithdrawnAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
