// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAppointment = `-- name: CancelAppointment :one
UPDATE appointments
SET status = 'cancelled', cancelled_by = $1,
    cancelled_at = now(), cancellation_reason = $2
WHERE id = $3 AND status IN ('proposed', 'scheduled')
RETURNING id, application_id, organization_id, kind, status, starts_at, ends_at, timezone, location_name, address, latitude, longitude, instructions, otp_required, created_by, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at
`

type CancelAppointmentParams struct {
	CancelledBy        pgtype.UUID `db:"cancelled_by" json:"cancelled_by"`
	CancellationReason *string     `db:"cancellation_reason" json:"cancellation_reason"`
	ID                 pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) CancelAppointment(ctx context.Context, arg CancelAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, cancelAppointment, arg.CancelledBy, arg.CancellationReason, arg.ID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OrganizationID,
		&i.Kind,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.LocationName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Instructions,
		&i.OtpRequired,
		&i.CreatedBy,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeAppointment = `-- name: CompleteAppointment :one
UPDATE appointments
SET status = 'completed'
WHERE id = $1 AND status = 'scheduled'
RETURNING id, application_id, organization_id, kind, status, starts_at, ends_at, timezone, location_name, address, latitude, longitude, instructions, otp_required, created_by, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at
`

func (q *Queries) CompleteAppointment(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, completeAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OrganizationID,
		&i.Kind,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.LocationName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Instructions,
		&i.OtpRequired,
		&i.CreatedBy,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeAppointmentOTP = `-- name: ConsumeAppointmentOTP :execrows
UPDATE appointment_otps
SET used_at = now()
WHERE id = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
  AND failed_attempts < max_attempts
`

func (q *Queries) ConsumeAppointmentOTP(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeAppointmentOTP, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
    application_id, organization_id, kind, starts_at, ends_at, timezone,
    location_name, address, latitude, longitude, instructions, otp_required, created_by
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13
)
RETURNING id, application_id, organization_id, kind, status, starts_at, ends_at, timezone, location_name, address, latitude, longitude, instructions, otp_required, created_by, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at
`

type CreateAppointmentParams struct {
	ApplicationID  pgtype.UUID        `db:"application_id" json:"application_id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Kind           string             `db:"kind" json:"kind"`
	StartsAt       pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt         pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	Timezone       string             `db:"timezone" json:"timezone"`
	LocationName   string             `db:"location_name" json:"location_name"`
	Address        string             `db:"address" json:"address"`
	Latitude       pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude      pgtype.Numeric     `db:"longitude" json:"longitude"`
	Instructions   string             `db:"instructions" json:"instructions"`
	OtpRequired    bool               `db:"otp_required" json:"otp_required"`
	CreatedBy      pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ApplicationID,
		arg.OrganizationID,
		arg.Kind,
		arg.StartsAt,
		arg.EndsAt,
		arg.Timezone,
		arg.LocationName,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Instructions,
		arg.OtpRequired,
		arg.CreatedBy,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OrganizationID,
		&i.Kind,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.LocationName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Instructions,
		&i.OtpRequired,
		&i.CreatedBy,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAppointmentOTP = `-- name: CreateAppointmentOTP :one
INSERT INTO appointment_otps (
    appointment_id, code_hash, expires_at, max_attempts, created_by
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING id, appointment_id, code_hash, expires_at, max_attempts, failed_attempts, used_at, revoked_at, created_by, created_at
`

type CreateAppointmentOTPParams struct {
	AppointmentID pgtype.UUID        `db:"appointment_id" json:"appointment_id"`
	CodeHash      []byte             `db:"code_hash" json:"code_hash"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	MaxAttempts   int16              `db:"max_attempts" json:"max_attempts"`
	CreatedBy     pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAppointmentOTP(ctx context.Context, arg CreateAppointmentOTPParams) (AppointmentOtp, error) {
	row := q.db.QueryRow(ctx, createAppointmentOTP,
		arg.AppointmentID,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.MaxAttempts,
		arg.CreatedBy,
	)
	var i AppointmentOtp
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.MaxAttempts,
		&i.FailedAttempts,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAppointmentOTP = `-- name: GetActiveAppointmentOTP :one
SELECT id, appointment_id, code_hash, expires_at, max_attempts, failed_attempts, used_at, revoked_at, created_by, created_at FROM appointment_otps
WHERE appointment_id = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
  AND failed_attempts < max_attempts
FOR UPDATE
`

func (q *Queries) GetActiveAppointmentOTP(ctx context.Context, appointmentID pgtype.UUID) (AppointmentOtp, error) {
	row := q.db.QueryRow(ctx, getActiveAppointmentOTP, appointmentID)
	var i AppointmentOtp
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.MaxAttempts,
		&i.FailedAttempts,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, application_id, organization_id, kind, status, starts_at, ends_at, timezone, location_name, address, latitude, longitude, instructions, otp_required, created_by, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at FROM appointments WHERE id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OrganizationID,
		&i.Kind,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.LocationName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Instructions,
		&i.OtpRequired,
		&i.CreatedBy,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAppointmentOTPFailure = `-- name: IncrementAppointmentOTPFailure :execrows
UPDATE appointment_otps
SET failed_attempts = failed_attempts + 1
WHERE id = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND failed_attempts < max_attempts
`

func (q *Queries) IncrementAppointmentOTPFailure(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementAppointmentOTPFailure, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listApplicationAppointments = `-- name: ListApplicationAppointments :many
SELECT id, application_id, organization_id, kind, status, starts_at, ends_at, timezone, location_name, address, latitude, longitude, instructions, otp_required, created_by, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at FROM appointments
WHERE application_id = $1
ORDER BY starts_at DESC, id
`

func (q *Queries) ListApplicationAppointments(ctx context.Context, applicationID pgtype.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listApplicationAppointments, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.OrganizationID,
			&i.Kind,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.LocationName,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Instructions,
			&i.OtpRequired,
			&i.CreatedBy,
			&i.CancelledBy,
			&i.CancelledAt,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentConfirmations = `-- name: ListAppointmentConfirmations :many
SELECT id, appointment_id, party, confirmed_by, confirmation, confirmed_at, notes FROM appointment_confirmations
WHERE appointment_id = $1
ORDER BY confirmed_at, id
`

func (q *Queries) ListAppointmentConfirmations(ctx context.Context, appointmentID pgtype.UUID) ([]AppointmentConfirmation, error) {
	rows, err := q.db.Query(ctx, listAppointmentConfirmations, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppointmentConfirmation{}
	for rows.Next() {
		var i AppointmentConfirmation
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.Party,
			&i.ConfirmedBy,
			&i.Confirmation,
			&i.ConfirmedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingOrganizationAppointments = `-- name: ListUpcomingOrganizationAppointments :many
SELECT ap.id, ap.application_id, ap.organization_id, ap.kind, ap.status, ap.starts_at, ap.ends_at, ap.timezone, ap.location_name, ap.address, ap.latitude, ap.longitude, ap.instructions, ap.otp_required, ap.created_by, ap.cancelled_by, ap.cancelled_at, ap.cancellation_reason, ap.created_at, ap.updated_at, a.name AS animal_name, u.display_name AS adopter_name
FROM appointments ap
JOIN adoption_applications aa ON aa.id = ap.application_id
JOIN animals a ON a.id = aa.animal_id
JOIN users u ON u.id = aa.adopter_id
WHERE ap.organization_id = $1
  AND ap.status IN ('proposed', 'scheduled')
  AND ap.starts_at >= $2
  AND ap.starts_at < $3
ORDER BY ap.starts_at, ap.id
`

type ListUpcomingOrganizationAppointmentsParams struct {
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	StartsAfter    pgtype.Timestamptz `db:"starts_after" json:"starts_after"`
	StartsBefore   pgtype.Timestamptz `db:"starts_before" json:"starts_before"`
}

type ListUpcomingOrganizationAppointmentsRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ApplicationID      pgtype.UUID        `db:"application_id" json:"application_id"`
	OrganizationID     pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Kind               string             `db:"kind" json:"kind"`
	Status             string             `db:"status" json:"status"`
	StartsAt           pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt             pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	Timezone           string             `db:"timezone" json:"timezone"`
	LocationName       string             `db:"location_name" json:"location_name"`
	Address            string             `db:"address" json:"address"`
	Latitude           pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude          pgtype.Numeric     `db:"longitude" json:"longitude"`
	Instructions       string             `db:"instructions" json:"instructions"`
	OtpRequired        bool               `db:"otp_required" json:"otp_required"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	CancelledBy        pgtype.UUID        `db:"cancelled_by" json:"cancelled_by"`
	CancelledAt        pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CancellationReason *string            `db:"cancellation_reason" json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AnimalName         string             `db:"animal_name" json:"animal_name"`
	AdopterName        string             `db:"adopter_name" json:"adopter_name"`
}

func (q *Queries) ListUpcomingOrganizationAppointments(ctx context.Context, arg ListUpcomingOrganizationAppointmentsParams) ([]ListUpcomingOrganizationAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingOrganizationAppointments, arg.OrganizationID, arg.StartsAfter, arg.StartsBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingOrganizationAppointmentsRow{}
	for rows.Next() {
		var i ListUpcomingOrganizationAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.OrganizationID,
			&i.Kind,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.LocationName,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Instructions,
			&i.OtpRequired,
			&i.CreatedBy,
			&i.CancelledBy,
			&i.CancelledAt,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnimalName,
			&i.AdopterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAppointmentOTP = `-- name: RevokeAppointmentOTP :execrows
UPDATE appointment_otps
SET revoked_at = now()
WHERE appointment_id = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAppointmentOTP(ctx context.Context, appointmentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAppointmentOTP, appointmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduleAppointment = `-- name: ScheduleAppointment :one
UPDATE appointments
SET status = 'scheduled', starts_at = $1, ends_at = $2,
    timezone = $3, location_name = $4,
    address = $5, latitude = $6,
    longitude = $7, instructions = $8
WHERE id = $9 AND status IN ('proposed', 'scheduled')
RETURNING id, application_id, organization_id, kind, status, starts_at, ends_at, timezone, location_name, address, latitude, longitude, instructions, otp_required, created_by, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at
`

type ScheduleAppointmentParams struct {
	StartsAt     pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt       pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	Timezone     string             `db:"timezone" json:"timezone"`
	LocationName string             `db:"location_name" json:"location_name"`
	Address      string             `db:"address" json:"address"`
	Latitude     pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude    pgtype.Numeric     `db:"longitude" json:"longitude"`
	Instructions string             `db:"instructions" json:"instructions"`
	ID           pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) ScheduleAppointment(ctx context.Context, arg ScheduleAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, scheduleAppointment,
		arg.StartsAt,
		arg.EndsAt,
		arg.Timezone,
		arg.LocationName,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Instructions,
		arg.ID,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OrganizationID,
		&i.Kind,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.LocationName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Instructions,
		&i.OtpRequired,
		&i.CreatedBy,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppointmentConfirmation = `-- name: UpsertAppointmentConfirmation :one
INSERT INTO appointment_confirmations (
    appointment_id, party, confirmed_by, confirmation, notes
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (appointment_id, party, confirmation) DO UPDATE
SET confirmed_by = EXCLUDED.confirmed_by,
    confirmed_at = now(),
    notes = EXCLUDED.notes
RETURNING id, appointment_id, party, confirmed_by, confirmation, confirmed_at, notes
`

type UpsertAppointmentConfirmationParams struct {
	AppointmentID pgtype.UUID `db:"appointment_id" json:"appointment_id"`
	Party         string      `db:"party" json:"party"`
	ConfirmedBy   pgtype.UUID `db:"confirmed_by" json:"confirmed_by"`
	Confirmation  string      `db:"confirmation" json:"confirmation"`
	Notes         *string     `db:"notes" json:"notes"`
}

func (q *Queries) UpsertAppointmentConfirmation(ctx context.Context, arg UpsertAppointmentConfirmationParams) (AppointmentConfirmation, error) {
	row := q.db.QueryRow(ctx, upsertAppointmentConfirmation,
		arg.AppointmentID,
		arg.Party,
		arg.ConfirmedBy,
		arg.Confirmation,
		arg.Notes,
	)
	var i AppointmentConfirmation
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.Party,
		&i.ConfirmedBy,
		&i.Confirmation,
		&i.ConfirmedAt,
		&i.Notes,
	)
	return i, err
}
