// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (
    actor_user_id, organization_id, action, entity_type, entity_id,
    old_values, new_values, metadata, request_id, ip_address
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10
)
RETURNING id, actor_user_id, organization_id, action, entity_type, entity_id, old_values, new_values, metadata, request_id, ip_address, created_at
`

type CreateAuditLogParams struct {
	ActorUserID    pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Action         string      `db:"action" json:"action"`
	EntityType     string      `db:"entity_type" json:"entity_type"`
	EntityID       pgtype.UUID `db:"entity_id" json:"entity_id"`
	OldValues      []byte      `db:"old_values" json:"old_values"`
	NewValues      []byte      `db:"new_values" json:"new_values"`
	Metadata       []byte      `db:"metadata" json:"metadata"`
	RequestID      pgtype.UUID `db:"request_id" json:"request_id"`
	IpAddress      *netip.Addr `db:"ip_address" json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.OrganizationID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
		arg.Metadata,
		arg.RequestID,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.OrganizationID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.OldValues,
		&i.NewValues,
		&i.Metadata,
		&i.RequestID,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listActorAuditLog = `-- name: ListActorAuditLog :many
SELECT id, actor_user_id, organization_id, action, entity_type, entity_id, old_values, new_values, metadata, request_id, ip_address, created_at FROM audit_log
WHERE actor_user_id = $1
  AND created_at >= $2
ORDER BY created_at DESC, id DESC
LIMIT $4::int OFFSET $3::int
`

type ListActorAuditLogParams struct {
	ActorUserID  pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	CreatedAfter pgtype.Timestamptz `db:"created_after" json:"created_after"`
	PageOffset   int32              `db:"page_offset" json:"page_offset"`
	PageSize     int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListActorAuditLog(ctx context.Context, arg ListActorAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listActorAuditLog,
		arg.ActorUserID,
		arg.CreatedAfter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.OrganizationID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValues,
			&i.NewValues,
			&i.Metadata,
			&i.RequestID,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityAuditLog = `-- name: ListEntityAuditLog :many
SELECT id, actor_user_id, organization_id, action, entity_type, entity_id, old_values, new_values, metadata, request_id, ip_address, created_at FROM audit_log
WHERE entity_type = $1
  AND entity_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $4::int OFFSET $3::int
`

type ListEntityAuditLogParams struct {
	EntityType string      `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
	PageOffset int32       `db:"page_offset" json:"page_offset"`
	PageSize   int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListEntityAuditLog(ctx context.Context, arg ListEntityAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listEntityAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.OrganizationID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValues,
			&i.NewValues,
			&i.Metadata,
			&i.RequestID,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
