// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :execrows
UPDATE password_reset_tokens
SET used_at = now()
WHERE id = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumePasswordResetToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, revoked_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash []byte             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (
    user_id, token_hash, user_agent, ip_address, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING id, user_id, token_hash, user_agent, ip_address, expires_at, last_used_at, revoked_at, revoke_reason, replaced_by_id, created_at
`

type CreateRefreshSessionParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash []byte             `db:"token_hash" json:"token_hash"`
	UserAgent *string            `db:"user_agent" json:"user_agent"`
	IpAddress *netip.Addr        `db:"ip_address" json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ReplacedByID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :execrows
DELETE FROM password_reset_tokens
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRefreshSessions = `-- name: DeleteExpiredRefreshSessions :execrows
DELETE FROM refresh_sessions
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshSessions(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshSessions, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivePasswordResetTokenByHash = `-- name: GetActivePasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, revoked_at, created_at FROM password_reset_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetActivePasswordResetTokenByHash(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getActivePasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveRefreshSessionByTokenHash = `-- name: GetActiveRefreshSessionByTokenHash :one
SELECT id, user_id, token_hash, user_agent, ip_address, expires_at, last_used_at, revoked_at, revoke_reason, replaced_by_id, created_at FROM refresh_sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetActiveRefreshSessionByTokenHash(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getActiveRefreshSessionByTokenHash, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ReplacedByID,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshSessions = `-- name: RevokeAllUserRefreshSessions :execrows
UPDATE refresh_sessions
SET revoked_at = now(), revoke_reason = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeAllUserRefreshSessionsParams struct {
	RevokeReason *string     `db:"revoke_reason" json:"revoke_reason"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeAllUserRefreshSessions(ctx context.Context, arg RevokeAllUserRefreshSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshSessions, arg.RevokeReason, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :execrows
UPDATE refresh_sessions
SET revoked_at = now(), revoke_reason = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeRefreshSessionParams struct {
	RevokeReason *string     `db:"revoke_reason" json:"revoke_reason"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) RevokeRefreshSession(ctx context.Context, arg RevokeRefreshSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshSession, arg.RevokeReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserPasswordResetTokens = `-- name: RevokeUserPasswordResetTokens :execrows
UPDATE password_reset_tokens
SET revoked_at = now()
WHERE user_id = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
`

func (q *Queries) RevokeUserPasswordResetTokens(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserPasswordResetTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRefreshSession = `-- name: RotateRefreshSession :execrows
UPDATE refresh_sessions
SET revoked_at = now(),
    revoke_reason = 'rotated',
    replaced_by_id = $1,
    last_used_at = now()
WHERE id = $2
  AND revoked_at IS NULL
  AND replaced_by_id IS NULL
  AND expires_at > now()
`

type RotateRefreshSessionParams struct {
	ReplacedByID pgtype.UUID `db:"replaced_by_id" json:"replaced_by_id"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateRefreshSession, arg.ReplacedByID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchRefreshSession = `-- name: TouchRefreshSession :execrows
UPDATE refresh_sessions
SET last_used_at = now()
WHERE id = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) TouchRefreshSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchRefreshSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
