// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeConversation = `-- name: CloseConversation :one
UPDATE conversations
SET status = $1, closed_by = $2, closed_at = now()
WHERE id = $3 AND status = 'open'
RETURNING id, organization_id, kind, animal_id, application_id, counterparty_user_id, status, closed_by, closed_at, created_at, updated_at
`

type CloseConversationParams struct {
	Status   string      `db:"status" json:"status"`
	ClosedBy pgtype.UUID `db:"closed_by" json:"closed_by"`
	ID       pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) CloseConversation(ctx context.Context, arg CloseConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, closeConversation, arg.Status, arg.ClosedBy, arg.ID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.AnimalID,
		&i.ApplicationID,
		&i.CounterpartyUserID,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdopterConversation = `-- name: CreateAdopterConversation :one
INSERT INTO conversations (
    organization_id, kind, animal_id, application_id, counterparty_user_id
)
SELECT aa.organization_id, 'adopter_organization', aa.animal_id, aa.id, aa.adopter_id
FROM adoption_applications aa
WHERE aa.id = $1
RETURNING id, organization_id, kind, animal_id, application_id, counterparty_user_id, status, closed_by, closed_at, created_at, updated_at
`

func (q *Queries) CreateAdopterConversation(ctx context.Context, applicationID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, createAdopterConversation, applicationID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.AnimalID,
		&i.ApplicationID,
		&i.CounterpartyUserID,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAnimalOwnerConversation = `-- name: CreateAnimalOwnerConversation :one
INSERT INTO conversations (
    organization_id, kind, animal_id, counterparty_user_id
)
SELECT a.responsible_organization_id, 'owner_organization', a.id, a.submitted_by
FROM animals a
WHERE a.id = $1
  AND a.responsible_organization_id IS NOT NULL
  AND a.deleted_at IS NULL
RETURNING id, organization_id, kind, animal_id, application_id, counterparty_user_id, status, closed_by, closed_at, created_at, updated_at
`

func (q *Queries) CreateAnimalOwnerConversation(ctx context.Context, animalID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, createAnimalOwnerConversation, animalID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.AnimalID,
		&i.ApplicationID,
		&i.CounterpartyUserID,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, body)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, body, moderation_status, moderation_reason, moderated_by, moderated_at, edited_at, deleted_at, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `db:"conversation_id" json:"conversation_id"`
	SenderID       pgtype.UUID `db:"sender_id" json:"sender_id"`
	Body           string      `db:"body" json:"body"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const editMessage = `-- name: EditMessage :one
UPDATE messages
SET body = $1, edited_at = now()
WHERE id = $2
  AND sender_id = $3
  AND deleted_at IS NULL
  AND moderation_status = 'visible'
RETURNING id, conversation_id, sender_id, body, moderation_status, moderation_reason, moderated_by, moderated_at, edited_at, deleted_at, created_at
`

type EditMessageParams struct {
	Body     string      `db:"body" json:"body"`
	ID       pgtype.UUID `db:"id" json:"id"`
	SenderID pgtype.UUID `db:"sender_id" json:"sender_id"`
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, editMessage, arg.Body, arg.ID, arg.SenderID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, organization_id, kind, animal_id, application_id, counterparty_user_id, status, closed_by, closed_at, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.AnimalID,
		&i.ApplicationID,
		&i.CounterpartyUserID,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT id, conversation_id, sender_id, body, moderation_status, moderation_reason, moderated_by, moderated_at, edited_at, deleted_at, created_at FROM messages
WHERE conversation_id = $1
  AND ($2::boolean OR moderation_status IN ('visible', 'flagged'))
  AND ($3::timestamptz IS NULL OR created_at < $3)
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListConversationMessagesParams struct {
	ConversationID   pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	IncludeModerated bool               `db:"include_moderated" json:"include_moderated"`
	BeforeCreatedAt  pgtype.Timestamptz `db:"before_created_at" json:"before_created_at"`
	PageSize         int32              `db:"page_size" json:"page_size"`
}

func (q *Queries) ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listConversationMessages,
		arg.ConversationID,
		arg.IncludeModerated,
		arg.BeforeCreatedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.ModerationStatus,
			&i.ModerationReason,
			&i.ModeratedBy,
			&i.ModeratedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationConversations = `-- name: ListOrganizationConversations :many
SELECT c.id, c.organization_id, c.kind, c.animal_id, c.application_id, c.counterparty_user_id, c.status, c.closed_by, c.closed_at, c.created_at, c.updated_at, a.name AS animal_name, u.display_name AS counterparty_name,
       latest.body AS last_message_body, latest.created_at AS last_message_at
FROM conversations c
JOIN animals a ON a.id = c.animal_id
JOIN users u ON u.id = c.counterparty_user_id
LEFT JOIN LATERAL (
    SELECT m.body, m.created_at
    FROM messages m
    WHERE m.conversation_id = c.id AND m.deleted_at IS NULL
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 1
) latest ON true
WHERE c.organization_id = $1
  AND ($2::text IS NULL OR c.status = $2)
ORDER BY COALESCE(latest.created_at, c.created_at) DESC, c.id
LIMIT $4::int OFFSET $3::int
`

type ListOrganizationConversationsParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Status         *string     `db:"status" json:"status"`
	PageOffset     int32       `db:"page_offset" json:"page_offset"`
	PageSize       int32       `db:"page_size" json:"page_size"`
}

type ListOrganizationConversationsRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	OrganizationID     pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Kind               string             `db:"kind" json:"kind"`
	AnimalID           pgtype.UUID        `db:"animal_id" json:"animal_id"`
	ApplicationID      pgtype.UUID        `db:"application_id" json:"application_id"`
	CounterpartyUserID pgtype.UUID        `db:"counterparty_user_id" json:"counterparty_user_id"`
	Status             string             `db:"status" json:"status"`
	ClosedBy           pgtype.UUID        `db:"closed_by" json:"closed_by"`
	ClosedAt           pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AnimalName         string             `db:"animal_name" json:"animal_name"`
	CounterpartyName   string             `db:"counterparty_name" json:"counterparty_name"`
	LastMessageBody    string             `db:"last_message_body" json:"last_message_body"`
	LastMessageAt      pgtype.Timestamptz `db:"last_message_at" json:"last_message_at"`
}

func (q *Queries) ListOrganizationConversations(ctx context.Context, arg ListOrganizationConversationsParams) ([]ListOrganizationConversationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationConversations,
		arg.OrganizationID,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationConversationsRow{}
	for rows.Next() {
		var i ListOrganizationConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Kind,
			&i.AnimalID,
			&i.ApplicationID,
			&i.CounterpartyUserID,
			&i.Status,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnimalName,
			&i.CounterpartyName,
			&i.LastMessageBody,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT c.id, c.organization_id, c.kind, c.animal_id, c.application_id, c.counterparty_user_id, c.status, c.closed_by, c.closed_at, c.created_at, c.updated_at, a.name AS animal_name, o.display_name AS organization_name,
       latest.body AS last_message_body, latest.created_at AS last_message_at
FROM conversations c
JOIN animals a ON a.id = c.animal_id
JOIN organizations o ON o.id = c.organization_id
LEFT JOIN LATERAL (
    SELECT m.body, m.created_at
    FROM messages m
    WHERE m.conversation_id = c.id AND m.deleted_at IS NULL
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 1
) latest ON true
WHERE c.counterparty_user_id = $1
ORDER BY COALESCE(latest.created_at, c.created_at) DESC, c.id
LIMIT $3::int OFFSET $2::int
`

type ListUserConversationsParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	PageOffset int32       `db:"page_offset" json:"page_offset"`
	PageSize   int32       `db:"page_size" json:"page_size"`
}

type ListUserConversationsRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	OrganizationID     pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Kind               string             `db:"kind" json:"kind"`
	AnimalID           pgtype.UUID        `db:"animal_id" json:"animal_id"`
	ApplicationID      pgtype.UUID        `db:"application_id" json:"application_id"`
	CounterpartyUserID pgtype.UUID        `db:"counterparty_user_id" json:"counterparty_user_id"`
	Status             string             `db:"status" json:"status"`
	ClosedBy           pgtype.UUID        `db:"closed_by" json:"closed_by"`
	ClosedAt           pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AnimalName         string             `db:"animal_name" json:"animal_name"`
	OrganizationName   string             `db:"organization_name" json:"organization_name"`
	LastMessageBody    string             `db:"last_message_body" json:"last_message_body"`
	LastMessageAt      pgtype.Timestamptz `db:"last_message_at" json:"last_message_at"`
}

func (q *Queries) ListUserConversations(ctx context.Context, arg ListUserConversationsParams) ([]ListUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, listUserConversations, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserConversationsRow{}
	for rows.Next() {
		var i ListUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Kind,
			&i.AnimalID,
			&i.ApplicationID,
			&i.CounterpartyUserID,
			&i.Status,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnimalName,
			&i.OrganizationName,
			&i.LastMessageBody,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderateMessage = `-- name: ModerateMessage :one
UPDATE messages
SET moderation_status = $1,
    moderation_reason = $2,
    moderated_by = $3,
    moderated_at = now()
WHERE id = $4
RETURNING id, conversation_id, sender_id, body, moderation_status, moderation_reason, moderated_by, moderated_at, edited_at, deleted_at, created_at
`

type ModerateMessageParams struct {
	ModerationStatus string      `db:"moderation_status" json:"moderation_status"`
	ModerationReason *string     `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID `db:"moderated_by" json:"moderated_by"`
	ID               pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ModerateMessage(ctx context.Context, arg ModerateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, moderateMessage,
		arg.ModerationStatus,
		arg.ModerationReason,
		arg.ModeratedBy,
		arg.ID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :execrows
UPDATE messages
SET deleted_at = now()
WHERE id = $1 AND sender_id = $2 AND deleted_at IS NULL
`

type SoftDeleteMessageParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SenderID pgtype.UUID `db:"sender_id" json:"sender_id"`
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMessage, arg.ID, arg.SenderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
