// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdoptionApplication struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	AnimalID         pgtype.UUID        `db:"animal_id" json:"animal_id"`
	AdopterID        pgtype.UUID        `db:"adopter_id" json:"adopter_id"`
	OrganizationID   pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Status           string             `db:"status" json:"status"`
	ApplicantMessage string             `db:"applicant_message" json:"applicant_message"`
	DecisionReason   *string            `db:"decision_reason" json:"decision_reason"`
	DecidedBy        pgtype.UUID        `db:"decided_by" json:"decided_by"`
	DecidedAt        pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	WithdrawnAt      pgtype.Timestamptz `db:"withdrawn_at" json:"withdrawn_at"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Animal struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	SubmittedBy               pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	ResponsibleOrganizationID pgtype.UUID        `db:"responsible_organization_id" json:"responsible_organization_id"`
	Source                    string             `db:"source" json:"source"`
	Status                    string             `db:"status" json:"status"`
	OrganizationReviewStatus  string             `db:"organization_review_status" json:"organization_review_status"`
	OrganizationReviewNotes   *string            `db:"organization_review_notes" json:"organization_review_notes"`
	ReviewedBy                pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt                pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	Name                      string             `db:"name" json:"name"`
	Species                   string             `db:"species" json:"species"`
	Breed                     *string            `db:"breed" json:"breed"`
	Sex                       string             `db:"sex" json:"sex"`
	Size                      string             `db:"size" json:"size"`
	BirthDate                 pgtype.Date        `db:"birth_date" json:"birth_date"`
	ApproximateAgeMonths      *int32             `db:"approximate_age_months" json:"approximate_age_months"`
	Description               string             `db:"description" json:"description"`
	HealthNotes               string             `db:"health_notes" json:"health_notes"`
	BehaviorNotes             string             `db:"behavior_notes" json:"behavior_notes"`
	Vaccinated                *bool              `db:"vaccinated" json:"vaccinated"`
	Neutered                  *bool              `db:"neutered" json:"neutered"`
	SpecialNeeds              bool               `db:"special_needs" json:"special_needs"`
	City                      string             `db:"city" json:"city"`
	StateCode                 string             `db:"state_code" json:"state_code"`
	CountryCode               string             `db:"country_code" json:"country_code"`
	Latitude                  pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude                 pgtype.Numeric     `db:"longitude" json:"longitude"`
	PublishedAt               pgtype.Timestamptz `db:"published_at" json:"published_at"`
	UnavailableReason         *string            `db:"unavailable_reason" json:"unavailable_reason"`
	AdoptedAt                 pgtype.Timestamptz `db:"adopted_at" json:"adopted_at"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AnimalImage struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	AnimalID         pgtype.UUID        `db:"animal_id" json:"animal_id"`
	StorageKey       string             `db:"storage_key" json:"storage_key"`
	AltText          string             `db:"alt_text" json:"alt_text"`
	Position         int16              `db:"position" json:"position"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
	RemovedAt        pgtype.Timestamptz `db:"removed_at" json:"removed_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AnimalPreference struct {
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	AnimalID   pgtype.UUID        `db:"animal_id" json:"animal_id"`
	Preference string             `db:"preference" json:"preference"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ApplicationScreening struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ApplicationID pgtype.UUID        `db:"application_id" json:"application_id"`
	Version       int32              `db:"version" json:"version"`
	Questions     []byte             `db:"questions" json:"questions"`
	Answers       []byte             `db:"answers" json:"answers"`
	Status        string             `db:"status" json:"status"`
	RequestedBy   pgtype.UUID        `db:"requested_by" json:"requested_by"`
	SubmittedAt   pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	ReviewedBy    pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt    pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	Outcome       *string            `db:"outcome" json:"outcome"`
	PrivateNotes  *string            `db:"private_notes" json:"private_notes"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ApplicationStatusHistory struct {
	ID            int64              `db:"id" json:"id"`
	ApplicationID pgtype.UUID        `db:"application_id" json:"application_id"`
	FromStatus    *string            `db:"from_status" json:"from_status"`
	ToStatus      string             `db:"to_status" json:"to_status"`
	Reason        *string            `db:"reason" json:"reason"`
	ChangedBy     pgtype.UUID        `db:"changed_by" json:"changed_by"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Appointment struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ApplicationID      pgtype.UUID        `db:"application_id" json:"application_id"`
	OrganizationID     pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Kind               string             `db:"kind" json:"kind"`
	Status             string             `db:"status" json:"status"`
	StartsAt           pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt             pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	Timezone           string             `db:"timezone" json:"timezone"`
	LocationName       string             `db:"location_name" json:"location_name"`
	Address            string             `db:"address" json:"address"`
	Latitude           pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude          pgtype.Numeric     `db:"longitude" json:"longitude"`
	Instructions       string             `db:"instructions" json:"instructions"`
	OtpRequired        bool               `db:"otp_required" json:"otp_required"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	CancelledBy        pgtype.UUID        `db:"cancelled_by" json:"cancelled_by"`
	CancelledAt        pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CancellationReason *string            `db:"cancellation_reason" json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppointmentConfirmation struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	AppointmentID pgtype.UUID        `db:"appointment_id" json:"appointment_id"`
	Party         string             `db:"party" json:"party"`
	ConfirmedBy   pgtype.UUID        `db:"confirmed_by" json:"confirmed_by"`
	Confirmation  string             `db:"confirmation" json:"confirmation"`
	ConfirmedAt   pgtype.Timestamptz `db:"confirmed_at" json:"confirmed_at"`
	Notes         *string            `db:"notes" json:"notes"`
}

type AppointmentOtp struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	AppointmentID  pgtype.UUID        `db:"appointment_id" json:"appointment_id"`
	CodeHash       []byte             `db:"code_hash" json:"code_hash"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	MaxAttempts    int16              `db:"max_attempts" json:"max_attempts"`
	FailedAttempts int16              `db:"failed_attempts" json:"failed_attempts"`
	UsedAt         pgtype.Timestamptz `db:"used_at" json:"used_at"`
	RevokedAt      pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedBy      pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuditLog struct {
	ID             int64              `db:"id" json:"id"`
	ActorUserID    pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Action         string             `db:"action" json:"action"`
	EntityType     string             `db:"entity_type" json:"entity_type"`
	EntityID       pgtype.UUID        `db:"entity_id" json:"entity_id"`
	OldValues      []byte             `db:"old_values" json:"old_values"`
	NewValues      []byte             `db:"new_values" json:"new_values"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	RequestID      pgtype.UUID        `db:"request_id" json:"request_id"`
	IpAddress      *netip.Addr        `db:"ip_address" json:"ip_address"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Conversation struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	OrganizationID     pgtype.UUID        `db:"organization_id" json:"organization_id"`
	Kind               string             `db:"kind" json:"kind"`
	AnimalID           pgtype.UUID        `db:"animal_id" json:"animal_id"`
	ApplicationID      pgtype.UUID        `db:"application_id" json:"application_id"`
	CounterpartyUserID pgtype.UUID        `db:"counterparty_user_id" json:"counterparty_user_id"`
	Status             string             `db:"status" json:"status"`
	ClosedBy           pgtype.UUID        `db:"closed_by" json:"closed_by"`
	ClosedAt           pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Message struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	ConversationID   pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	SenderID         pgtype.UUID        `db:"sender_id" json:"sender_id"`
	Body             string             `db:"body" json:"body"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason *string            `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
	EditedAt         pgtype.Timestamptz `db:"edited_at" json:"edited_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Organization struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	LegalName          string             `db:"legal_name" json:"legal_name"`
	DisplayName        string             `db:"display_name" json:"display_name"`
	Slug               string             `db:"slug" json:"slug"`
	RegistrationNumber *string            `db:"registration_number" json:"registration_number"`
	Description        string             `db:"description" json:"description"`
	OfficialEmail      string             `db:"official_email" json:"official_email"`
	OfficialPhone      *string            `db:"official_phone" json:"official_phone"`
	WebsiteUrl         *string            `db:"website_url" json:"website_url"`
	City               string             `db:"city" json:"city"`
	StateCode          string             `db:"state_code" json:"state_code"`
	CountryCode        string             `db:"country_code" json:"country_code"`
	Latitude           pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude          pgtype.Numeric     `db:"longitude" json:"longitude"`
	VerificationStatus string             `db:"verification_status" json:"verification_status"`
	VerificationNotes  *string            `db:"verification_notes" json:"verification_notes"`
	VerifiedBy         pgtype.UUID        `db:"verified_by" json:"verified_by"`
	VerifiedAt         pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	DeactivatedAt      pgtype.Timestamptz `db:"deactivated_at" json:"deactivated_at"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OrganizationMember struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	OrganizationID        pgtype.UUID        `db:"organization_id" json:"organization_id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	MemberRole            string             `db:"member_role" json:"member_role"`
	Status                string             `db:"status" json:"status"`
	CanManageMembers      bool               `db:"can_manage_members" json:"can_manage_members"`
	CanPublishAnimals     bool               `db:"can_publish_animals" json:"can_publish_animals"`
	CanManageApplications bool               `db:"can_manage_applications" json:"can_manage_applications"`
	InvitedBy             pgtype.UUID        `db:"invited_by" json:"invited_by"`
	JoinedAt              pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	DeactivatedAt         pgtype.Timestamptz `db:"deactivated_at" json:"deactivated_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash []byte             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PostAdoptionFollowup struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ApplicationID  pgtype.UUID        `db:"application_id" json:"application_id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ContactMethod  string             `db:"contact_method" json:"contact_method"`
	Notes          string             `db:"notes" json:"notes"`
	WelfareStatus  string             `db:"welfare_status" json:"welfare_status"`
	RecordedBy     pgtype.UUID        `db:"recorded_by" json:"recorded_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RefreshSession struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash    []byte             `db:"token_hash" json:"token_hash"`
	UserAgent    *string            `db:"user_agent" json:"user_agent"`
	IpAddress    *netip.Addr        `db:"ip_address" json:"ip_address"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt   pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt    pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason *string            `db:"revoke_reason" json:"revoke_reason"`
	ReplacedByID pgtype.UUID        `db:"replaced_by_id" json:"replaced_by_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Report struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ReporterID     pgtype.UUID        `db:"reporter_id" json:"reporter_id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	AnimalID       pgtype.UUID        `db:"animal_id" json:"animal_id"`
	ApplicationID  pgtype.UUID        `db:"application_id" json:"application_id"`
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	MessageID      pgtype.UUID        `db:"message_id" json:"message_id"`
	Category       string             `db:"category" json:"category"`
	Description    string             `db:"description" json:"description"`
	Status         string             `db:"status" json:"status"`
	Priority       string             `db:"priority" json:"priority"`
	AssignedTo     pgtype.UUID        `db:"assigned_to" json:"assigned_to"`
	Resolution     *string            `db:"resolution" json:"resolution"`
	ResolvedBy     pgtype.UUID        `db:"resolved_by" json:"resolved_by"`
	ResolvedAt     pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Role struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Key         string             `db:"key" json:"key"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Email             string             `db:"email" json:"email"`
	PasswordHash      string             `db:"password_hash" json:"password_hash"`
	DisplayName       string             `db:"display_name" json:"display_name"`
	Phone             *string            `db:"phone" json:"phone"`
	City              *string            `db:"city" json:"city"`
	StateCode         *string            `db:"state_code" json:"state_code"`
	CountryCode       string             `db:"country_code" json:"country_code"`
	Latitude          pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude         pgtype.Numeric     `db:"longitude" json:"longitude"`
	TermsAcceptedAt   pgtype.Timestamptz `db:"terms_accepted_at" json:"terms_accepted_at"`
	PrivacyAcceptedAt pgtype.Timestamptz `db:"privacy_accepted_at" json:"privacy_accepted_at"`
	EmailVerifiedAt   pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	DeactivatedAt     pgtype.Timestamptz `db:"deactivated_at" json:"deactivated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserRole struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	RoleID    pgtype.UUID        `db:"role_id" json:"role_id"`
	GrantedBy pgtype.UUID        `db:"granted_by" json:"granted_by"`
	GrantedAt pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
}
