// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignReport = `-- name: AssignReport :one
UPDATE reports
SET assigned_to = $1,
    status = CASE WHEN status = 'open' THEN 'triaged' ELSE status END
WHERE id = $2 AND status NOT IN ('resolved', 'dismissed')
RETURNING id, reporter_id, organization_id, animal_id, application_id, conversation_id, message_id, category, description, status, priority, assigned_to, resolution, resolved_by, resolved_at, created_at, updated_at
`

type AssignReportParams struct {
	AssignedTo pgtype.UUID `db:"assigned_to" json:"assigned_to"`
	ID         pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) AssignReport(ctx context.Context, arg AssignReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, assignReport, arg.AssignedTo, arg.ID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.OrganizationID,
		&i.AnimalID,
		&i.ApplicationID,
		&i.ConversationID,
		&i.MessageID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    reporter_id, organization_id, animal_id, application_id,
    conversation_id, message_id, category, description, priority
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
RETURNING id, reporter_id, organization_id, animal_id, application_id, conversation_id, message_id, category, description, status, priority, assigned_to, resolution, resolved_by, resolved_at, created_at, updated_at
`

type CreateReportParams struct {
	ReporterID     pgtype.UUID `db:"reporter_id" json:"reporter_id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	AnimalID       pgtype.UUID `db:"animal_id" json:"animal_id"`
	ApplicationID  pgtype.UUID `db:"application_id" json:"application_id"`
	ConversationID pgtype.UUID `db:"conversation_id" json:"conversation_id"`
	MessageID      pgtype.UUID `db:"message_id" json:"message_id"`
	Category       string      `db:"category" json:"category"`
	Description    string      `db:"description" json:"description"`
	Priority       string      `db:"priority" json:"priority"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.OrganizationID,
		arg.AnimalID,
		arg.ApplicationID,
		arg.ConversationID,
		arg.MessageID,
		arg.Category,
		arg.Description,
		arg.Priority,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.OrganizationID,
		&i.AnimalID,
		&i.ApplicationID,
		&i.ConversationID,
		&i.MessageID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, reporter_id, organization_id, animal_id, application_id, conversation_id, message_id, category, description, status, priority, assigned_to, resolution, resolved_by, resolved_at, created_at, updated_at FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.OrganizationID,
		&i.AnimalID,
		&i.ApplicationID,
		&i.ConversationID,
		&i.MessageID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenReports = `-- name: ListOpenReports :many
SELECT r.id, r.reporter_id, r.organization_id, r.animal_id, r.application_id, r.conversation_id, r.message_id, r.category, r.description, r.status, r.priority, r.assigned_to, r.resolution, r.resolved_by, r.resolved_at, r.created_at, r.updated_at, u.display_name AS reporter_name
FROM reports r
JOIN users u ON u.id = r.reporter_id
WHERE r.status NOT IN ('resolved', 'dismissed')
  AND ($1::uuid IS NULL OR r.organization_id = $1)
  AND ($2::uuid IS NULL OR r.assigned_to = $2)
ORDER BY
    CASE r.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 WHEN 'normal' THEN 2 ELSE 3 END,
    r.created_at,
    r.id
LIMIT $4::int OFFSET $3::int
`

type ListOpenReportsParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	AssignedTo     pgtype.UUID `db:"assigned_to" json:"assigned_to"`
	PageOffset     int32       `db:"page_offset" json:"page_offset"`
	PageSize       int32       `db:"page_size" json:"page_size"`
}

type ListOpenReportsRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ReporterID     pgtype.UUID        `db:"reporter_id" json:"reporter_id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	AnimalID       pgtype.UUID        `db:"animal_id" json:"animal_id"`
	ApplicationID  pgtype.UUID        `db:"application_id" json:"application_id"`
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	MessageID      pgtype.UUID        `db:"message_id" json:"message_id"`
	Category       string             `db:"category" json:"category"`
	Description    string             `db:"description" json:"description"`
	Status         string             `db:"status" json:"status"`
	Priority       string             `db:"priority" json:"priority"`
	AssignedTo     pgtype.UUID        `db:"assigned_to" json:"assigned_to"`
	Resolution     *string            `db:"resolution" json:"resolution"`
	ResolvedBy     pgtype.UUID        `db:"resolved_by" json:"resolved_by"`
	ResolvedAt     pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ReporterName   string             `db:"reporter_name" json:"reporter_name"`
}

func (q *Queries) ListOpenReports(ctx context.Context, arg ListOpenReportsParams) ([]ListOpenReportsRow, error) {
	rows, err := q.db.Query(ctx, listOpenReports,
		arg.OrganizationID,
		arg.AssignedTo,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenReportsRow{}
	for rows.Next() {
		var i ListOpenReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.OrganizationID,
			&i.AnimalID,
			&i.ApplicationID,
			&i.ConversationID,
			&i.MessageID,
			&i.Category,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReporterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :one
UPDATE reports
SET status = $1, resolution = $2,
    resolved_by = $3, resolved_at = now()
WHERE id = $4
  AND status NOT IN ('resolved', 'dismissed')
  AND $1::text IN ('resolved', 'dismissed')
RETURNING id, reporter_id, organization_id, animal_id, application_id, conversation_id, message_id, category, description, status, priority, assigned_to, resolution, resolved_by, resolved_at, created_at, updated_at
`

type ResolveReportParams struct {
	Status     string      `db:"status" json:"status"`
	Resolution *string     `db:"resolution" json:"resolution"`
	ResolvedBy pgtype.UUID `db:"resolved_by" json:"resolved_by"`
	ID         pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, resolveReport,
		arg.Status,
		arg.Resolution,
		arg.ResolvedBy,
		arg.ID,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.OrganizationID,
		&i.AnimalID,
		&i.ApplicationID,
		&i.ConversationID,
		&i.MessageID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setReportStatus = `-- name: SetReportStatus :one
UPDATE reports
SET status = $1
WHERE id = $2 AND status NOT IN ('resolved', 'dismissed')
RETURNING id, reporter_id, organization_id, animal_id, application_id, conversation_id, message_id, category, description, status, priority, assigned_to, resolution, resolved_by, resolved_at, created_at, updated_at
`

type SetReportStatusParams struct {
	Status string      `db:"status" json:"status"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SetReportStatus(ctx context.Context, arg SetReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, setReportStatus, arg.Status, arg.ID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.OrganizationID,
		&i.AnimalID,
		&i.ApplicationID,
		&i.ConversationID,
		&i.MessageID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
