// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptOrganizationMembership = `-- name: AcceptOrganizationMembership :one
UPDATE organization_members
SET status = 'active', joined_at = now(), deactivated_at = NULL
WHERE id = $1 AND user_id = $2 AND status = 'invited'
RETURNING id, organization_id, user_id, member_role, status, can_manage_members, can_publish_animals, can_manage_applications, invited_by, joined_at, deactivated_at, created_at, updated_at
`

type AcceptOrganizationMembershipParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) AcceptOrganizationMembership(ctx context.Context, arg AcceptOrganizationMembershipParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, acceptOrganizationMembership, arg.ID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.MemberRole,
		&i.Status,
		&i.CanManageMembers,
		&i.CanPublishAnimals,
		&i.CanManageApplications,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    legal_name, display_name, slug, registration_number, description,
    official_email, official_phone, website_url, city, state_code,
    country_code, latitude, longitude, created_by
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14
)
RETURNING id, legal_name, display_name, slug, registration_number, description, official_email, official_phone, website_url, city, state_code, country_code, latitude, longitude, verification_status, verification_notes, verified_by, verified_at, deactivated_at, created_by, created_at, updated_at
`

type CreateOrganizationParams struct {
	LegalName          string         `db:"legal_name" json:"legal_name"`
	DisplayName        string         `db:"display_name" json:"display_name"`
	Slug               string         `db:"slug" json:"slug"`
	RegistrationNumber *string        `db:"registration_number" json:"registration_number"`
	Description        string         `db:"description" json:"description"`
	OfficialEmail      string         `db:"official_email" json:"official_email"`
	OfficialPhone      *string        `db:"official_phone" json:"official_phone"`
	WebsiteUrl         *string        `db:"website_url" json:"website_url"`
	City               string         `db:"city" json:"city"`
	StateCode          string         `db:"state_code" json:"state_code"`
	CountryCode        string         `db:"country_code" json:"country_code"`
	Latitude           pgtype.Numeric `db:"latitude" json:"latitude"`
	Longitude          pgtype.Numeric `db:"longitude" json:"longitude"`
	CreatedBy          pgtype.UUID    `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.LegalName,
		arg.DisplayName,
		arg.Slug,
		arg.RegistrationNumber,
		arg.Description,
		arg.OfficialEmail,
		arg.OfficialPhone,
		arg.WebsiteUrl,
		arg.City,
		arg.StateCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedBy,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.DisplayName,
		&i.Slug,
		&i.RegistrationNumber,
		&i.Description,
		&i.OfficialEmail,
		&i.OfficialPhone,
		&i.WebsiteUrl,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.DeactivatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateOrganization = `-- name: DeactivateOrganization :execrows
UPDATE organizations
SET deactivated_at = now(),
    verification_status = CASE WHEN verification_status = 'verified' THEN 'suspended' ELSE verification_status END
WHERE id = $1 AND deactivated_at IS NULL
`

func (q *Queries) DeactivateOrganization(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateOrganization, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveOrganizationMember = `-- name: GetActiveOrganizationMember :one
SELECT id, organization_id, user_id, member_role, status, can_manage_members, can_publish_animals, can_manage_applications, invited_by, joined_at, deactivated_at, created_at, updated_at FROM organization_members
WHERE organization_id = $1
  AND user_id = $2
  AND status = 'active'
`

type GetActiveOrganizationMemberParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetActiveOrganizationMember(ctx context.Context, arg GetActiveOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getActiveOrganizationMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.MemberRole,
		&i.Status,
		&i.CanManageMembers,
		&i.CanPublishAnimals,
		&i.CanManageApplications,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, legal_name, display_name, slug, registration_number, description, official_email, official_phone, website_url, city, state_code, country_code, latitude, longitude, verification_status, verification_notes, verified_by, verified_at, deactivated_at, created_by, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.DisplayName,
		&i.Slug,
		&i.RegistrationNumber,
		&i.Description,
		&i.OfficialEmail,
		&i.OfficialPhone,
		&i.WebsiteUrl,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.DeactivatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicOrganizationBySlug = `-- name: GetPublicOrganizationBySlug :one
SELECT o.id, o.legal_name, o.display_name, o.slug, o.registration_number, o.description, o.official_email, o.official_phone, o.website_url, o.city, o.state_code, o.country_code, o.latitude, o.longitude, o.verification_status, o.verification_notes, o.verified_by, o.verified_at, o.deactivated_at, o.created_by, o.created_at, o.updated_at,
       count(a.id) FILTER (WHERE a.status = 'available' AND a.deleted_at IS NULL) AS available_animals
FROM organizations o
LEFT JOIN animals a ON a.responsible_organization_id = o.id
WHERE o.slug = $1
  AND o.verification_status = 'verified'
  AND o.deactivated_at IS NULL
GROUP BY o.id
`

type GetPublicOrganizationBySlugRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	LegalName          string             `db:"legal_name" json:"legal_name"`
	DisplayName        string             `db:"display_name" json:"display_name"`
	Slug               string             `db:"slug" json:"slug"`
	RegistrationNumber *string            `db:"registration_number" json:"registration_number"`
	Description        string             `db:"description" json:"description"`
	OfficialEmail      string             `db:"official_email" json:"official_email"`
	OfficialPhone      *string            `db:"official_phone" json:"official_phone"`
	WebsiteUrl         *string            `db:"website_url" json:"website_url"`
	City               string             `db:"city" json:"city"`
	StateCode          string             `db:"state_code" json:"state_code"`
	CountryCode        string             `db:"country_code" json:"country_code"`
	Latitude           pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude          pgtype.Numeric     `db:"longitude" json:"longitude"`
	VerificationStatus string             `db:"verification_status" json:"verification_status"`
	VerificationNotes  *string            `db:"verification_notes" json:"verification_notes"`
	VerifiedBy         pgtype.UUID        `db:"verified_by" json:"verified_by"`
	VerifiedAt         pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	DeactivatedAt      pgtype.Timestamptz `db:"deactivated_at" json:"deactivated_at"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AvailableAnimals   int64              `db:"available_animals" json:"available_animals"`
}

func (q *Queries) GetPublicOrganizationBySlug(ctx context.Context, slug string) (GetPublicOrganizationBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicOrganizationBySlug, slug)
	var i GetPublicOrganizationBySlugRow
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.DisplayName,
		&i.Slug,
		&i.RegistrationNumber,
		&i.Description,
		&i.OfficialEmail,
		&i.OfficialPhone,
		&i.WebsiteUrl,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.DeactivatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAnimals,
	)
	return i, err
}

const inviteOrganizationMember = `-- name: InviteOrganizationMember :one
INSERT INTO organization_members (
    organization_id, user_id, member_role, can_manage_members,
    can_publish_animals, can_manage_applications, invited_by
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
RETURNING id, organization_id, user_id, member_role, status, can_manage_members, can_publish_animals, can_manage_applications, invited_by, joined_at, deactivated_at, created_at, updated_at
`

type InviteOrganizationMemberParams struct {
	OrganizationID        pgtype.UUID `db:"organization_id" json:"organization_id"`
	UserID                pgtype.UUID `db:"user_id" json:"user_id"`
	MemberRole            string      `db:"member_role" json:"member_role"`
	CanManageMembers      bool        `db:"can_manage_members" json:"can_manage_members"`
	CanPublishAnimals     bool        `db:"can_publish_animals" json:"can_publish_animals"`
	CanManageApplications bool        `db:"can_manage_applications" json:"can_manage_applications"`
	InvitedBy             pgtype.UUID `db:"invited_by" json:"invited_by"`
}

func (q *Queries) InviteOrganizationMember(ctx context.Context, arg InviteOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, inviteOrganizationMember,
		arg.OrganizationID,
		arg.UserID,
		arg.MemberRole,
		arg.CanManageMembers,
		arg.CanPublishAnimals,
		arg.CanManageApplications,
		arg.InvitedBy,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.MemberRole,
		&i.Status,
		&i.CanManageMembers,
		&i.CanPublishAnimals,
		&i.CanManageApplications,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT om.id, om.organization_id, om.user_id, om.member_role, om.status, om.can_manage_members, om.can_publish_animals, om.can_manage_applications, om.invited_by, om.joined_at, om.deactivated_at, om.created_at, om.updated_at, u.display_name, u.email
FROM organization_members om
JOIN users u ON u.id = om.user_id
WHERE om.organization_id = $1
  AND ($2::text IS NULL OR om.status = $2)
ORDER BY om.created_at, om.id
`

type ListOrganizationMembersParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Status         *string     `db:"status" json:"status"`
}

type ListOrganizationMembersRow struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	OrganizationID        pgtype.UUID        `db:"organization_id" json:"organization_id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	MemberRole            string             `db:"member_role" json:"member_role"`
	Status                string             `db:"status" json:"status"`
	CanManageMembers      bool               `db:"can_manage_members" json:"can_manage_members"`
	CanPublishAnimals     bool               `db:"can_publish_animals" json:"can_publish_animals"`
	CanManageApplications bool               `db:"can_manage_applications" json:"can_manage_applications"`
	InvitedBy             pgtype.UUID        `db:"invited_by" json:"invited_by"`
	JoinedAt              pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	DeactivatedAt         pgtype.Timestamptz `db:"deactivated_at" json:"deactivated_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisplayName           string             `db:"display_name" json:"display_name"`
	Email                 string             `db:"email" json:"email"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, arg ListOrganizationMembersParams) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, arg.OrganizationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.MemberRole,
			&i.Status,
			&i.CanManageMembers,
			&i.CanPublishAnimals,
			&i.CanManageApplications,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedOrganizations = `-- name: ListVerifiedOrganizations :many
SELECT id, legal_name, display_name, slug, registration_number, description, official_email, official_phone, website_url, city, state_code, country_code, latitude, longitude, verification_status, verification_notes, verified_by, verified_at, deactivated_at, created_by, created_at, updated_at FROM organizations
WHERE verification_status = 'verified'
  AND deactivated_at IS NULL
  AND ($1::text IS NULL OR state_code = $1)
  AND ($2::text IS NULL OR city = $2)
ORDER BY display_name, id
LIMIT $4::int OFFSET $3::int
`

type ListVerifiedOrganizationsParams struct {
	StateCode  *string `db:"state_code" json:"state_code"`
	City       *string `db:"city" json:"city"`
	PageOffset int32   `db:"page_offset" json:"page_offset"`
	PageSize   int32   `db:"page_size" json:"page_size"`
}

func (q *Queries) ListVerifiedOrganizations(ctx context.Context, arg ListVerifiedOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listVerifiedOrganizations,
		arg.StateCode,
		arg.City,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.LegalName,
			&i.DisplayName,
			&i.Slug,
			&i.RegistrationNumber,
			&i.Description,
			&i.OfficialEmail,
			&i.OfficialPhone,
			&i.WebsiteUrl,
			&i.City,
			&i.StateCode,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.VerificationStatus,
			&i.VerificationNotes,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.DeactivatedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrganizationMember = `-- name: RemoveOrganizationMember :execrows
UPDATE organization_members
SET status = 'removed', deactivated_at = now()
WHERE id = $1 AND organization_id = $2 AND status IN ('invited', 'active')
`

type RemoveOrganizationMemberParams struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeOrganizationMember, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOrganizationVerification = `-- name: SetOrganizationVerification :one
UPDATE organizations
SET verification_status = $1,
    verification_notes = $2,
    verified_by = CASE WHEN $1::text = 'verified' THEN $3 ELSE verified_by END,
    verified_at = CASE WHEN $1::text = 'verified' THEN now() ELSE verified_at END
WHERE id = $4 AND deactivated_at IS NULL
RETURNING id, legal_name, display_name, slug, registration_number, description, official_email, official_phone, website_url, city, state_code, country_code, latitude, longitude, verification_status, verification_notes, verified_by, verified_at, deactivated_at, created_by, created_at, updated_at
`

type SetOrganizationVerificationParams struct {
	VerificationStatus string      `db:"verification_status" json:"verification_status"`
	VerificationNotes  *string     `db:"verification_notes" json:"verification_notes"`
	ActorID            pgtype.UUID `db:"actor_id" json:"actor_id"`
	ID                 pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SetOrganizationVerification(ctx context.Context, arg SetOrganizationVerificationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setOrganizationVerification,
		arg.VerificationStatus,
		arg.VerificationNotes,
		arg.ActorID,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.DisplayName,
		&i.Slug,
		&i.RegistrationNumber,
		&i.Description,
		&i.OfficialEmail,
		&i.OfficialPhone,
		&i.WebsiteUrl,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.DeactivatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationMemberPermissions = `-- name: UpdateOrganizationMemberPermissions :one
UPDATE organization_members
SET member_role = $1,
    can_manage_members = $2,
    can_publish_animals = $3,
    can_manage_applications = $4
WHERE id = $5 AND organization_id = $6 AND status = 'active'
RETURNING id, organization_id, user_id, member_role, status, can_manage_members, can_publish_animals, can_manage_applications, invited_by, joined_at, deactivated_at, created_at, updated_at
`

type UpdateOrganizationMemberPermissionsParams struct {
	MemberRole            string      `db:"member_role" json:"member_role"`
	CanManageMembers      bool        `db:"can_manage_members" json:"can_manage_members"`
	CanPublishAnimals     bool        `db:"can_publish_animals" json:"can_publish_animals"`
	CanManageApplications bool        `db:"can_manage_applications" json:"can_manage_applications"`
	ID                    pgtype.UUID `db:"id" json:"id"`
	OrganizationID        pgtype.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateOrganizationMemberPermissions(ctx context.Context, arg UpdateOrganizationMemberPermissionsParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMemberPermissions,
		arg.MemberRole,
		arg.CanManageMembers,
		arg.CanPublishAnimals,
		arg.CanManageApplications,
		arg.ID,
		arg.OrganizationID,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.MemberRole,
		&i.Status,
		&i.CanManageMembers,
		&i.CanPublishAnimals,
		&i.CanManageApplications,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationProfile = `-- name: UpdateOrganizationProfile :one
UPDATE organizations
SET display_name = $1,
    description = $2,
    official_email = $3,
    official_phone = $4,
    website_url = $5,
    city = $6,
    state_code = $7,
    country_code = $8,
    latitude = $9,
    longitude = $10
WHERE id = $11 AND deactivated_at IS NULL
RETURNING id, legal_name, display_name, slug, registration_number, description, official_email, official_phone, website_url, city, state_code, country_code, latitude, longitude, verification_status, verification_notes, verified_by, verified_at, deactivated_at, created_by, created_at, updated_at
`

type UpdateOrganizationProfileParams struct {
	DisplayName   string         `db:"display_name" json:"display_name"`
	Description   string         `db:"description" json:"description"`
	OfficialEmail string         `db:"official_email" json:"official_email"`
	OfficialPhone *string        `db:"official_phone" json:"official_phone"`
	WebsiteUrl    *string        `db:"website_url" json:"website_url"`
	City          string         `db:"city" json:"city"`
	StateCode     string         `db:"state_code" json:"state_code"`
	CountryCode   string         `db:"country_code" json:"country_code"`
	Latitude      pgtype.Numeric `db:"latitude" json:"latitude"`
	Longitude     pgtype.Numeric `db:"longitude" json:"longitude"`
	ID            pgtype.UUID    `db:"id" json:"id"`
}

func (q *Queries) UpdateOrganizationProfile(ctx context.Context, arg UpdateOrganizationProfileParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationProfile,
		arg.DisplayName,
		arg.Description,
		arg.OfficialEmail,
		arg.OfficialPhone,
		arg.WebsiteUrl,
		arg.City,
		arg.StateCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.DisplayName,
		&i.Slug,
		&i.RegistrationNumber,
		&i.Description,
		&i.OfficialEmail,
		&i.OfficialPhone,
		&i.WebsiteUrl,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.VerificationStatus,
		&i.VerificationNotes,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.DeactivatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
