// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAnimalPreference = `-- name: DeleteAnimalPreference :execrows
DELETE FROM animal_preferences
WHERE user_id = $1 AND animal_id = $2
`

type DeleteAnimalPreferenceParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	AnimalID pgtype.UUID `db:"animal_id" json:"animal_id"`
}

func (q *Queries) DeleteAnimalPreference(ctx context.Context, arg DeleteAnimalPreferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnimalPreference, arg.UserID, arg.AnimalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnimalPreference = `-- name: GetAnimalPreference :one
SELECT user_id, animal_id, preference, created_at, updated_at FROM animal_preferences
WHERE user_id = $1 AND animal_id = $2
`

type GetAnimalPreferenceParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	AnimalID pgtype.UUID `db:"animal_id" json:"animal_id"`
}

func (q *Queries) GetAnimalPreference(ctx context.Context, arg GetAnimalPreferenceParams) (AnimalPreference, error) {
	row := q.db.QueryRow(ctx, getAnimalPreference, arg.UserID, arg.AnimalID)
	var i AnimalPreference
	err := row.Scan(
		&i.UserID,
		&i.AnimalID,
		&i.Preference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPreferredAnimals = `-- name: ListPreferredAnimals :many
SELECT a.id, a.submitted_by, a.responsible_organization_id, a.source, a.status, a.organization_review_status, a.organization_review_notes, a.reviewed_by, a.reviewed_at, a.name, a.species, a.breed, a.sex, a.size, a.birth_date, a.approximate_age_months, a.description, a.health_notes, a.behavior_notes, a.vaccinated, a.neutered, a.special_needs, a.city, a.state_code, a.country_code, a.latitude, a.longitude, a.published_at, a.unavailable_reason, a.adopted_at, a.deleted_at, a.created_at, a.updated_at, p.preference, p.updated_at AS preference_updated_at,
       o.display_name AS organization_name, o.slug AS organization_slug
FROM animal_preferences p
JOIN animals a ON a.id = p.animal_id
LEFT JOIN organizations o ON o.id = a.responsible_organization_id
WHERE p.user_id = $1
  AND p.preference = $2
  AND a.deleted_at IS NULL
ORDER BY p.updated_at DESC, a.id
LIMIT $4::int OFFSET $3::int
`

type ListPreferredAnimalsParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	Preference string      `db:"preference" json:"preference"`
	PageOffset int32       `db:"page_offset" json:"page_offset"`
	PageSize   int32       `db:"page_size" json:"page_size"`
}

type ListPreferredAnimalsRow struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	SubmittedBy               pgtype.UUID        `db:"submitted_by" json:"submitted_by"`
	ResponsibleOrganizationID pgtype.UUID        `db:"responsible_organization_id" json:"responsible_organization_id"`
	Source                    string             `db:"source" json:"source"`
	Status                    string             `db:"status" json:"status"`
	OrganizationReviewStatus  string             `db:"organization_review_status" json:"organization_review_status"`
	OrganizationReviewNotes   *string            `db:"organization_review_notes" json:"organization_review_notes"`
	ReviewedBy                pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt                pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	Name                      string             `db:"name" json:"name"`
	Species                   string             `db:"species" json:"species"`
	Breed                     *string            `db:"breed" json:"breed"`
	Sex                       string             `db:"sex" json:"sex"`
	Size                      string             `db:"size" json:"size"`
	BirthDate                 pgtype.Date        `db:"birth_date" json:"birth_date"`
	ApproximateAgeMonths      *int32             `db:"approximate_age_months" json:"approximate_age_months"`
	Description               string             `db:"description" json:"description"`
	HealthNotes               string             `db:"health_notes" json:"health_notes"`
	BehaviorNotes             string             `db:"behavior_notes" json:"behavior_notes"`
	Vaccinated                *bool              `db:"vaccinated" json:"vaccinated"`
	Neutered                  *bool              `db:"neutered" json:"neutered"`
	SpecialNeeds              bool               `db:"special_needs" json:"special_needs"`
	City                      string             `db:"city" json:"city"`
	StateCode                 string             `db:"state_code" json:"state_code"`
	CountryCode               string             `db:"country_code" json:"country_code"`
	Latitude                  pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude                 pgtype.Numeric     `db:"longitude" json:"longitude"`
	PublishedAt               pgtype.Timestamptz `db:"published_at" json:"published_at"`
	UnavailableReason         *string            `db:"unavailable_reason" json:"unavailable_reason"`
	AdoptedAt                 pgtype.Timestamptz `db:"adopted_at" json:"adopted_at"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Preference                string             `db:"preference" json:"preference"`
	PreferenceUpdatedAt       pgtype.Timestamptz `db:"preference_updated_at" json:"preference_updated_at"`
	OrganizationName          *string            `db:"organization_name" json:"organization_name"`
	OrganizationSlug          *string            `db:"organization_slug" json:"organization_slug"`
}

func (q *Queries) ListPreferredAnimals(ctx context.Context, arg ListPreferredAnimalsParams) ([]ListPreferredAnimalsRow, error) {
	rows, err := q.db.Query(ctx, listPreferredAnimals,
		arg.UserID,
		arg.Preference,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreferredAnimalsRow{}
	for rows.Next() {
		var i ListPreferredAnimalsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.ResponsibleOrganizationID,
			&i.Source,
			&i.Status,
			&i.OrganizationReviewStatus,
			&i.OrganizationReviewNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Name,
			&i.Species,
			&i.Breed,
			&i.Sex,
			&i.Size,
			&i.BirthDate,
			&i.ApproximateAgeMonths,
			&i.Description,
			&i.HealthNotes,
			&i.BehaviorNotes,
			&i.Vaccinated,
			&i.Neutered,
			&i.SpecialNeeds,
			&i.City,
			&i.StateCode,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.PublishedAt,
			&i.UnavailableReason,
			&i.AdoptedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Preference,
			&i.PreferenceUpdatedAt,
			&i.OrganizationName,
			&i.OrganizationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnimalPreference = `-- name: UpsertAnimalPreference :one
INSERT INTO animal_preferences (user_id, animal_id, preference)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, animal_id) DO UPDATE
SET preference = EXCLUDED.preference
RETURNING user_id, animal_id, preference, created_at, updated_at
`

type UpsertAnimalPreferenceParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	AnimalID   pgtype.UUID `db:"animal_id" json:"animal_id"`
	Preference string      `db:"preference" json:"preference"`
}

func (q *Queries) UpsertAnimalPreference(ctx context.Context, arg UpsertAnimalPreferenceParams) (AnimalPreference, error) {
	row := q.db.QueryRow(ctx, upsertAnimalPreference, arg.UserID, arg.AnimalID, arg.Preference)
	var i AnimalPreference
	err := row.Scan(
		&i.UserID,
		&i.AnimalID,
		&i.Preference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
