// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, display_name, phone, city, state_code, country_code,
    latitude, longitude, terms_accepted_at, privacy_accepted_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11
)
RETURNING id, email, password_hash, display_name, phone, city, state_code, country_code, latitude, longitude, terms_accepted_at, privacy_accepted_at, email_verified_at, deactivated_at, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email             string             `db:"email" json:"email"`
	PasswordHash      string             `db:"password_hash" json:"password_hash"`
	DisplayName       string             `db:"display_name" json:"display_name"`
	Phone             *string            `db:"phone" json:"phone"`
	City              *string            `db:"city" json:"city"`
	StateCode         *string            `db:"state_code" json:"state_code"`
	CountryCode       string             `db:"country_code" json:"country_code"`
	Latitude          pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude         pgtype.Numeric     `db:"longitude" json:"longitude"`
	TermsAcceptedAt   pgtype.Timestamptz `db:"terms_accepted_at" json:"terms_accepted_at"`
	PrivacyAcceptedAt pgtype.Timestamptz `db:"privacy_accepted_at" json:"privacy_accepted_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Phone,
		arg.City,
		arg.StateCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.TermsAcceptedAt,
		arg.PrivacyAcceptedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Phone,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.TermsAcceptedAt,
		&i.PrivacyAcceptedAt,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :execrows
UPDATE users
SET deactivated_at = now()
WHERE id = $1 AND deactivated_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveUserByEmail = `-- name: GetActiveUserByEmail :one
SELECT id, email, password_hash, display_name, phone, city, state_code, country_code, latitude, longitude, terms_accepted_at, privacy_accepted_at, email_verified_at, deactivated_at, deleted_at, created_at, updated_at FROM users
WHERE email = $1
  AND deleted_at IS NULL
  AND deactivated_at IS NULL
`

func (q *Queries) GetActiveUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Phone,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.TermsAcceptedAt,
		&i.PrivacyAcceptedAt,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, phone, city, state_code, country_code, latitude, longitude, terms_accepted_at, privacy_accepted_at, email_verified_at, deactivated_at, deleted_at, created_at, updated_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Phone,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.TermsAcceptedAt,
		&i.PrivacyAcceptedAt,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantUserRole = `-- name: GrantUserRole :exec
INSERT INTO user_roles (user_id, role_id, granted_by)
SELECT $1, id, $2
FROM roles
WHERE key = $3
ON CONFLICT (user_id, role_id) DO NOTHING
`

type GrantUserRoleParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	GrantedBy pgtype.UUID `db:"granted_by" json:"granted_by"`
	RoleKey   string      `db:"role_key" json:"role_key"`
}

func (q *Queries) GrantUserRole(ctx context.Context, arg GrantUserRoleParams) error {
	_, err := q.db.Exec(ctx, grantUserRole, arg.UserID, arg.GrantedBy, arg.RoleKey)
	return err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.key, r.description, r.created_at
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.key
`

func (q *Queries) ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, now())
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, display_name, phone, city, state_code, country_code, latitude, longitude, terms_accepted_at, privacy_accepted_at, email_verified_at, deactivated_at, deleted_at, created_at, updated_at
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Phone,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.TermsAcceptedAt,
		&i.PrivacyAcceptedAt,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeUserRole = `-- name: RevokeUserRole :execrows
DELETE FROM user_roles ur
USING roles r
WHERE ur.role_id = r.id
  AND ur.user_id = $1
  AND r.key = $2
`

type RevokeUserRoleParams struct {
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	RoleKey string      `db:"role_key" json:"role_key"`
}

func (q *Queries) RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRole, arg.UserID, arg.RoleKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = now(), deactivated_at = COALESCE(deactivated_at, now())
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash = $1
WHERE id = $2 AND deleted_at IS NULL AND deactivated_at IS NULL
`

type UpdateUserPasswordParams struct {
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $1,
    phone = $2,
    city = $3,
    state_code = $4,
    country_code = $5,
    latitude = $6,
    longitude = $7
WHERE id = $8 AND deleted_at IS NULL AND deactivated_at IS NULL
RETURNING id, email, password_hash, display_name, phone, city, state_code, country_code, latitude, longitude, terms_accepted_at, privacy_accepted_at, email_verified_at, deactivated_at, deleted_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName string         `db:"display_name" json:"display_name"`
	Phone       *string        `db:"phone" json:"phone"`
	City        *string        `db:"city" json:"city"`
	StateCode   *string        `db:"state_code" json:"state_code"`
	CountryCode string         `db:"country_code" json:"country_code"`
	Latitude    pgtype.Numeric `db:"latitude" json:"latitude"`
	Longitude   pgtype.Numeric `db:"longitude" json:"longitude"`
	ID          pgtype.UUID    `db:"id" json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Phone,
		arg.City,
		arg.StateCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Phone,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.TermsAcceptedAt,
		&i.PrivacyAcceptedAt,
		&i.EmailVerifiedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
