// Command openapi exports documentation without connecting to a database.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/pet-finder-app/petfinder-api/internal/api"
)

func main() {
	output := flag.String("output", "build/openapi.yaml", "output path, or - for stdout")
	check := flag.Bool("check", false, "check an existing artifact instead of writing it")
	flag.Parse()
	if err := export(*output, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func export(output string, check bool) error {
	content, err := api.OpenAPI().YAML()
	if err != nil {
		return fmt.Errorf("generate OpenAPI: %w", err)
	}
	content = append([]byte("# Code generated by go run ./cmd/openapi. DO NOT EDIT.\n"), content...)
	if check {
		existing, err := os.ReadFile(output)
		if err != nil {
			return err
		}
		if !bytes.Equal(existing, content) {
			return fmt.Errorf("%s is outdated; run make docs-generate", output)
		}
		return nil
	}
	if output == "-" {
		_, err = os.Stdout.Write(content)
		return err
	}
	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		return err
	}
	return os.WriteFile(output, content, 0644)
}
